// Los textos del tutorial en en. Generado a partir de la versión original;
// para agregar un idioma, copiar este archivo y traducir los valores.
export const en = {
  ui: {
    "nav.play": "Tutorial",
    "nav.home": "Home",
    "nav.mine": "Mine",
    "nav.badges": "Badges",
    "nav.create": "Create",
    "mine.title": "Mine",
    "mine.projects": "projects",
    "mine.badges": "badges",
    "badges.title": "Badges",
    "app.title": "Introduction to Diálogo",
    "play.title": "Introduction to Diálogo",
    "play.subtitle": "A tutorial to get you started: play, learn the rules, then download Diálogo.",
    "play.goal": "Goal",
    "play.previous": "Previous level",
    "play.redo": "Play it again",
    "play.next": "Next challenge",
    "play.locked": "Finish the challenges to unlock",
    "play.builds": "Build your own games",
    "play.free": "Free creation",
    "play.startOver": "Start over from zero",
    "play.startOverConfirm": "Start over from zero? Your challenges and badges will be erased. Your projects stay.",
    "play.freeHint": "Unlocks when you finish building the games",
    "language": "Language",
    "sound": "Sound",
    "sound.on": "Sound: on",
    "sound.off": "Sound: off",
    "openFile": "Open a .dialog.ar file",
    "more": "More",
    "open": "Open",
    "copyAndChange": "Copy and change",
    "download": "Download .dialog.ar",
    "myVersionOf": "My version of ",
    "mineSuffix": " (mine)",
    "error.open": "Couldn't open the project",
    "error.copy": "Couldn't copy the project",
    "error.file": "Couldn't open the file",
    "error.openNamed": "Couldn't open: ",
    "feed.challenge": "Challenge",
    "feed.nextChallenge": "Your next challenge",
    "feed.play": "Play",
    "feed.live": "live",
    "feed.you": "You",
    "feed.empty": "Create your first project",
    "feed.watchOnly": "This project is for watching, not steering",
    "category.games": "Game",
    "category.didactic": "Lesson",
    "category.mine": "Mine",
    "success.title": "You did it!",
    "success.next": "Next",
    "success.home": "Home",
    "success.stay": "Stay and invent",
    "success.yours": "It's yours now. Change anything. You'll find it in Mine.",
    "menu.backToStart": "Back to start",
    "menu.forBuilding": "For building",
    "menu.setStart": "Set this as start",
    "menu.reuse": "Use tiles from other projects",
    "challenge.restart": "Start over",
    "tray.draw": "Draw",
    "tray.drawing": "Drawing",
    "tray.symbol": "Tile",
    "joystick.space": "Space",
    "joystick.enter": "Enter",
    "paint.title": "Draw",
    "paint.done": "Done",
    "paint.close": "Close without saving",
    "paint.brush": "Brush",
    "paint.eraser": "Eraser",
    "paint.bucket": "Bucket",
    "paint.undo": "Undo",
    "paint.size": "Size",
    "paint.canvas": "Canvas",
    "color.black": "Black",
    "color.orange": "Orange",
    "color.blue": "Blue",
    "color.brown": "Brown",
    "badge.first-drop": "First tile|Put a tile on the board",
    "badge.rule": "First rule|Make a rule with tiles",
    "badge.first-move": "On the move|Move the character for the first time",
    "badge.artist": "Artist|Draw a new tile",
    "badge.detective": "Detective|Use the eyes to see what a rule says",
    "badge.explorer": "Explorer|Open three projects",
    "badge.remix": "Inventor|Copy a project and change it",
    "badge.saver": "Collector|Save a project of yours",
    "badge.world": "World complete|Finish every challenge of a world",
    "badge.ladder": "Champion|Finish every challenge",
    "end.title": "Excellent!",
    "end.text": "You've completed the web tutorial. Now download the environment from dialog.ar and make your first chess project with your own drawings.",
    "end.download": "Download Diálogo",
    "end.watch": "Class 1: Chess (video)",
    "end.later": "Not now",
    "color.white": "White",
    "color.red": "Red",
    "color.yellow": "Yellow",
    "color.green": "Green",
    "color.purple": "Purple",
    "color.pink": "Pink",
    "color.cyan": "Sky blue",
    "color.gray": "Gray",
    "world.primeros": "First steps",
    "world.choques": "Collisions",
    "world.categorias": "Categories",
    "world.sustitucion": "Substitution",
    "world.metaprogramacion": "Rules that change",
    "world.naves": "Ships and time",
    "world.numeros": "Numbers",
    "world.puntos": "Score",
    "world.builds": "Build your own games",
  },
  challenges: {
    "reach-star": {
      title: "Reach the star",
      mission: "Get the character to the star.",
      steps: ["Take the character to the star with the arrows"],
      praise: "The character is next to the arrows: that is why it moves.",
    },
    "make-rule": {
      title: "Make the rule",
      mission: "Make the character move, then get it to the star.",
      steps: ["Drag the arrows to the little square, next to the character", "Now it moves! Take it to the star"],
      praise: "Character + arrows = it moves. That is a rule.",
    },
    "eat-star": {
      title: "Eat the stars",
      mission: "Make the character remove every star from the board.",
      steps: ["Drag the black hole to the little square at the end of the rule", "Now crash into both stars"],
      praise: "When the character crashes into a star, the star falls into the black hole: it disappears for good.",
    },
    "draw": {
      title: "Draw",
      mission: "Draw your own character.",
      steps: ["Tap the pencil. Draw your character"],
      praise: "Your drawing is a character now. Next, we make it move.",
    },
    "bring-to-life": {
      title: "Bring it to life",
      mission: "Bring your drawing to life and get it to the star.",
      steps: ["Drag your drawing to the little square, next to the arrows", "Your drawing moves! Take it to the star"],
      praise: "Your drawing + arrows = your drawing moves. You made that rule.",
    },
    "run": {
      title: "The monster runs",
      mission: "Make the monster reach the star on its own.",
      steps: ["Drag \"runs to\" to the little square, between the monster and the star", "Look: the monster runs by itself"],
      praise: "Monster + runs to + star: the monster goes to the star on its own, without you touching anything.",
    },
    "push": {
      title: "Push the box",
      mission: "Get the box onto the star.",
      steps: ["Drag \"pushes\" to the little square, between the character and the box", "Now push the box to the star"],
      praise: "Character + pushes + box: when the character crashes into the box, the box moves.",
    },
    "walls": {
      title: "The wall",
      mission: "Stop the monster with the wall so it never reaches you.",
      steps: ["Drag \"can't pass\" to the little square, between the monster and the wall", "Watch what the monster does"],
      praise: "Monster + can't pass + wall: the monster runs, but the wall stops it.",
    },
    "eyes": {
      title: "The eyes",
      mission: "See what a rule says, without playing.",
      steps: ["Drag the eyes to the little square, next to the star"],
      praise: "The eyes show what the rule says: here, the star becomes a heart.",
    },
    "sun": {
      title: "The sun comes out",
      mission: "Make the sun come out over the clouds.",
      steps: ["Drag \"teleport\" to the little square, between the sun and the cloud", "Take the sheep to the grass"],
      praise: "When the sheep crashes into the grass, the sun appears in the clouds. A crash can make things appear.",
    },
    "eat-all": {
      title: "Eat everything",
      mission: "Make the character remove every apple and every star.",
      steps: ["Drag the black hole to the little square", "Now eat the apples and the stars"],
      praise: "One rule for each thing you eat. With two rules, the character eats two things.",
    },
    "portal": {
      title: "The portal",
      mission: "Get the character across the wall to the star.",
      steps: ["Drag \"teleport\" to the little square, between the character and the door", "Go into the portal and reach the star"],
      praise: "Character crashes into portal → the character appears at the door. That is how you cross a wall.",
    },
    "pull": {
      title: "Pull the box",
      mission: "Take the box along with you to the star.",
      steps: ["Drag \"pulls\" to the little square, between the character and the box", "Take the character to the star. The box follows"],
      praise: "Character + pulls + box: the box goes behind the character.",
    },
    "nobody-passes": {
      title: "Nobody passes",
      mission: "Keep the ghost out and get to the star.",
      steps: ["Drag the wildcard to the little square, before \"can't pass\"", "Take the character to the star. The ghost can't pass"],
      praise: "The wildcard stands for anything: nobody passes the wall, not the ghost, not you.",
    },
    "food": {
      title: "It is all food",
      mission: "Make the character eat apples and fish: a balanced diet.",
      steps: ["Drag \"is inside\" to the little square, between the fish and the food", "Now eat everything"],
      praise: "The apple is inside food, and so is the fish: one rule eats both. That is a category.",
    },
    "one-rule": {
      title: "One rule for everything",
      mission: "Eat three different things with a single rule.",
      steps: ["Drag \"food\" to both little squares of the rule", "Now eat everything"],
      praise: "Three different things, one rule: the rule talks about the category, not about each thing.",
    },
    "day-night": {
      title: "Day and night",
      mission: "Turn the sun into the moon.",
      steps: ["Drag \"turns into\" to the little square, between the sun and the moon", "Now put the eyes next to the sun at the top"],
      praise: "Sun → moon: the sun turns into the moon. That is a substitution.",
    },
    "chain": {
      title: "In a chain",
      mission: "Turn the sun into a star, step by step.",
      steps: ["Drag \"turns into\" to the little square, between the moon and the star", "Now put the eyes next to the sun at the top"],
      praise: "Sun → moon → star: substitutions chain all the way to the end.",
    },
    "break-rule": {
      title: "Break the rule",
      mission: "Break your own rule to get through the wall.",
      steps: ["Push \"can't pass\" out of the rule", "Now walk through the wall to the star"],
      praise: "You pushed a piece of your program. The game changes its own rules while you play.",
    },
    "rule-by-playing": {
      title: "Make a rule by playing",
      mission: "Make a rule by pushing its pieces, then reach the star.",
      steps: ["Push \"pulls\" into the little square of the rule", "Now take the character to the star. The box follows"],
      praise: "You made a rule without the tray: by pushing its pieces around the board.",
    },
    "fire": {
      title: "Bullseye",
      mission: "Shoot an arrow at the ghost.",
      steps: ["Drag \"runs to\" to the little square, between the arrow and the ghost", "Tap the space bar"],
      praise: "The space bar makes the arrow appear at the ship, and the arrow runs to the ghost. Two rules, one bullseye.",
    },
    "missile": {
      title: "Make it vanish",
      mission: "Shoot the ghost down so it disappears.",
      steps: ["Drag the black hole to the little square at the end of the top rule", "Tap the space bar"],
      praise: "One more rule: when the arrow crashes into the ghost, the ghost falls into the black hole. It disappears for good.",
    },
    "next": {
      title: "The next one",
      mission: "Invent the number 3.",
      steps: ["Put the eyes next to the 2 at the top", "Now drag the 3 to the little square: the next one after 2 is 3"],
      praise: "There are no numbers in Diálogo: you invent them. \"Next of 2 → 3\" is a rule like any other.",
    },
    "score": {
      title: "Score",
      mission: "Make the score go up when you eat a star.",
      steps: ["Drag \"points to\" to the little square at the end of the rule", "Put the eyes next to the score", "Crash into both stars and watch the score"],
      praise: "Crashing does not set a number: it swaps the rule \"score → 0\" for \"score → the next one\". It adds one every time. No variables.",
    },
    "add-zero": {
      title: "Adding zero",
      mission: "Teach Diálogo to add zero.",
      steps: ["Put the eyes next to the 2 at the top", "Now drag \"number\" to the little square at the end of the rule"],
      praise: "Zero plus a number is that number. Addition starts with that rule: the base case.",
    },
    "build-chess": {
      title: "Chess",
      mission: "Tap the pencil and draw a black piece",
      steps: ["Tap the pencil and draw a black piece", "Now draw a white piece", "Put a black piece and a white piece on the board", "Make the rule: black piece · arrows", "Make the eating rule: black · bumps · white · turns into · white · teleport · black hole", "Eat the white piece"],
      praise: "You built a tiny chess: your pieces, your rules. The real one adds categories: \"black piece\" for all the black ones.",
    },
  },
};
