// Los textos del tutorial en en. Generado a partir de la versión original;
// para agregar un idioma, copiar este archivo y traducir los valores.
export const en = {
  ui: {
    "nav.play": "Sequence",
    "nav.home": "Home",
    "nav.mine": "Mine",
    "nav.badges": "Badges",
    "nav.create": "Create",
    "mine.title": "Mine",
    "mine.projects": "projects",
    "mine.badges": "badges",
    "badges.title": "Badges",
    "app.title": "Introduction to Diálogo",
    "play.title": "An introduction by playing",
    "play.subtitle": "A fun introduction: play, get to know the basic symbols, then download Diálogo on your computer and build the projects.",
    "play.goal": "Goal",
    "play.previous": "Previous level",
    "play.redo": "Play it again",
    "play.next": "Next challenge",
    "play.locked": "Finish the challenges to unlock",
    "play.builds": "Build your own games",
    "play.free": "Free creation",
    "play.startOver": "Start over from zero",
    "play.startOverConfirm": "Start over from zero? Your challenges and badges will be erased.",
    "play.freeHint": "Unlocks when you finish building the games",
    "language": "Language",
    "sound": "Sound",
    "sound.on": "Sound: on",
    "sound.off": "Sound: off",
    "openFile": "Open a .dialog.ar file",
    "more": "More",
    "open": "Open",
    "copyAndChange": "Copy and change",
    "download": "Download .dialog.ar",
    "myVersionOf": "My version of",
    "mineSuffix": "(mine)",
    "error.open": "Couldn't open the project",
    "error.copy": "Couldn't copy the project",
    "error.file": "Couldn't open the file",
    "error.openNamed": "Couldn't open:",
    "feed.challenge": "Challenge",
    "feed.nextChallenge": "Your next challenge",
    "feed.play": "Play",
    "feed.live": "live",
    "feed.you": "You",
    "feed.empty": "Create your first project",
    "feed.watchOnly": "This project is for watching, not steering",
    "category.games": "Game",
    "category.didactic": "Lesson",
    "category.mine": "Mine",
    "success.title": "You did it!",
    "success.next": "Next",
    "success.home": "Home",
    "success.stay": "Stay and invent",
    "success.yours": "It's yours now. Change anything. You'll find it in Mine.",
    "menu.backToStart": "Back to start",
    "menu.forBuilding": "For building",
    "menu.setStart": "Set this as start",
    "menu.reuse": "Use tiles from other projects",
    "challenge.restart": "Start over",
    "tray.draw": "Draw",
    "tray.drawing": "Drawing",
    "tray.symbol": "Tile",
    "joystick.space": "Space",
    "joystick.enter": "Enter",
    "paint.title": "Draw",
    "paint.done": "Done",
    "paint.close": "Close without saving",
    "paint.brush": "Brush",
    "paint.eraser": "Eraser",
    "paint.bucket": "Bucket",
    "paint.undo": "Undo",
    "paint.size": "Size",
    "paint.canvas": "Canvas",
    "color.black": "Black",
    "color.orange": "Orange",
    "color.blue": "Blue",
    "color.brown": "Brown",
    "badge.first-drop": "First tile|Put a tile on the board",
    "badge.rule": "First rule|Make a rule with tiles",
    "badge.first-move": "On the move|Move the character for the first time",
    "badge.artist": "Artist|Draw a new tile",
    "badge.detective": "Detective|Use the eyes to see what a rule says",
    "badge.explorer": "Explorer|Open three projects",
    "badge.remix": "Inventor|Copy a project and change it",
    "badge.saver": "Collector|Save a project of yours",
    "badge.world": "World complete|Finish every challenge of a world",
    "badge.ladder": "Champion|Finish every challenge",
    "end.title": "Congratulations!",
    "end.text": "You understand the basics of Diálogo now. You can go on with the projects through the video tutorials. The next step is to download Diálogo and then do the first chess project.",
    "end.note": "Diálogo runs on a computer: you cannot go on from the phone.",
    "end.download": "Download Diálogo on a computer",
    "end.watch": "Class 1: Chess (video)",
    "end.later": "Not now",
    "color.white": "White",
    "color.red": "Red",
    "color.yellow": "Yellow",
    "color.green": "Green",
    "color.purple": "Purple",
    "color.pink": "Pink",
    "color.cyan": "Sky blue",
    "color.gray": "Gray",
    "world.primeros": "First steps",
    "world.choques": "Collisions",
    "world.categorias": "Categories",
    "world.sustitucion": "Substitution",
    "world.metaprogramacion": "Rules that change",
    "world.naves": "Ships and time",
    "world.numeros": "Numbers",
    "world.puntos": "Score",
    "world.builds": "Build your own games",
  },
  challenges: {
    "reach-star": {
      title: "Journey to the stars",
      mission: "Get the character to the star.",
      steps: ["Move the character with the arrows"],
      praise: "The character symbol is next to the arrows symbol: that is why it moves.",
    },
    "make-rule": {
      title: "Make your first rule",
      mission: "Take the character to the star.",
      steps: ["Drag the arrows next to the character symbol", "It can move now! Take it to the star"],
      praise: "Character + arrows = it moves. That is a rule.",
    },
    "eat-star": {
      title: "Eat the stars",
      mission: "Make the character wipe every star off the board.",
      steps: ["Drag the black hole and complete the rule", "Now move onto both stars"],
      praise: "When the character crashes into a star, the star falls into the black hole: it disappears for good.",
    },
    "draw": {
      title: "Draw",
      mission: "Draw your own character.",
      steps: ["Tap the pencil. Draw."],
      praise: "Your drawing is a character now. Next, we make it move.",
    },
    "bring-to-life": {
      title: "Bring your character to life",
      mission: "Take your character to the star.",
      steps: ["Drag your character symbol next to the arrows one", "Your character can move! Take it to the star"],
      praise: "Your drawing + arrows = your drawing moves. You made that rule.",
    },
    "run": {
      title: "The monster runs",
      mission: "Make the monster go to the star on its own.",
      steps: ["Put \"runs to\" between the monster symbol and the star one", "Look: the monster runs by itself"],
      praise: "Monster + runs to + star: the monster goes to the star on its own, without you touching anything.",
    },
    "push": {
      title: "Space delivery",
      mission: "Take the parcel to the star.",
      steps: ["Drag \"pushes\" between the character symbol and the box one", "Move with the arrows and push the box to the star"],
      praise: "Character + pushes + box: the character can push boxes.",
    },
    "walls": {
      title: "Set the limits of movement",
      mission: "Keep the monster on the other side of the wall.",
      steps: ["Drag \"can't pass\" between the monster symbol and the wall one", "Watch what the monster does"],
      praise: "Monster + can't pass + wall: the monster cannot go through walls.",
    },
    "eyes": {
      title: "The eyes",
      mission: "See what a rule says, without playing.",
      steps: ["Drag the eyes to the little square, next to the star"],
      praise: "The eyes show what the rule says: here, the star becomes a heart.",
    },
    "sun": {
      title: "The sun comes out",
      mission: "Make the sun come out over the clouds.",
      steps: ["Drag \"teleport\" between the sun symbol and the cloud one", "Move the sheep to the grass"],
      praise: "When the sheep crashes into the grass, the sun appears in the cloud. A collision can make things appear.",
    },
    "eat-all": {
      title: "Eat lots of fruit, and stars too",
      mission: "Make the character wipe out every apple and every star.",
      steps: ["Drag the black hole where it belongs", "Now move onto the apples and the stars"],
      praise: "One rule for each thing you eat. With two rules, the character eats two things.",
    },
    "portal": {
      title: "The portal",
      mission: "Teleport to the other side of the wall and reach the star.",
      steps: ["Drag \"teleport\" between the character symbol and the door one", "Go into the portal and reach the star"],
      praise: "Character crashes into portal → the character appears at the door. That is how a character teleports.",
    },
    "pull": {
      title: "Pulling things",
      mission: "Take the box along with you to the star.",
      steps: ["Drag \"pulls\" between the character symbol and the box one", "Take the character to the star. The box follows"],
      praise: "Character + pulls + box: the box goes behind the character.",
    },
    "nobody-passes": {
      title: "Nobody passes",
      mission: "Keep the ghost trapped and reach the star.",
      steps: ["Drag the wildcard next to \"can't pass\"", "Take the character to the star. The ghost cannot reach it"],
      praise: "The wildcard stands for anything: no character can go through the wall, neither the ghost nor you.",
    },
    "food": {
      title: "A balanced diet",
      mission: "Make the character eat apples and fish.",
      steps: ["Drag \"is inside\" between the fish symbol and the food one", "Now eat everything"],
      praise: "The apple is inside the idea of food, and so is the fish: one rule lets you eat different foods. That is a category.",
    },
    "one-rule": {
      title: "One rule for many things",
      mission: "Eat three different things with a single rule.",
      steps: ["Drag the \"food\" symbol and complete the rule", "Now eat everything"],
      praise: "Three different things, one rule: the rule talks about the abstract category, not about each concrete thing.",
    },
    "day-night": {
      title: "Night comes from day",
      mission: "Turn the sun into the moon.",
      steps: ["Drag \"turns into\" between the sun symbol and the moon one", "Now put the eyes next to the sun symbol, the one higher up"],
      praise: "Sun → moon: the sun turns into the moon. That is a rule that substitutes one symbol for another.",
    },
    "chain": {
      title: "A chain of changes",
      mission: "Turn the sun into a star, step by step.",
      steps: ["Drag \"turns into\" between the moon symbol and the star one", "Now put the eyes next to the sun symbol at the top"],
      praise: "Sun → moon → star: substitutions chain all the way to the end.",
    },
    "break-rule": {
      title: "Erase the rule by playing",
      mission: "Break your own rule so you can cross the wall.",
      steps: ["Push any symbol of the rule that stops you from going through the wall", "Now walk through the wall to the star"],
      praise: "The character can change rules. The game changes its own rules while you play.",
    },
    "rule-by-playing": {
      title: "Make the rule by playing",
      mission: "Make a rule by pushing symbols and reach the star.",
      steps: ["Push \"pulls\" between the two loose symbols", "Now take the character to the box and go over the star. The box follows"],
      praise: "You made a rule without taking tiles from the bar: by pushing symbols around the board.",
    },
    "fire": {
      title: "Bullseye",
      mission: "Shoot an arrow at the ghost.",
      steps: ["Drag \"runs to\" to the little square, between the arrow and the ghost", "Tap the space bar"],
      praise: "The space bar makes the arrow appear at the ship, and the arrow runs to the ghost. Two rules, one bullseye.",
    },
    "missile": {
      title: "Make it vanish",
      mission: "Shoot the ghost down with an arrow.",
      steps: ["Drag the black hole to the little square at the end of the top rule", "Tap the space bar"],
      praise: "When the arrow crashes into the ghost, the ghost falls into the black hole. It disappears for good.",
    },
    "next": {
      title: "The next number",
      mission: "Connect the numbers.",
      steps: ["Put the eyes next to the 2 at the top", "Now drag the 3 to the little square: the next one after 2 is 3"],
      praise: "There are no numbers in Diálogo: you invent them. \"Next of 2 → 3\" is a rule like any other.",
    },
    "score": {
      title: "Score",
      mission: "Make the score go up when you touch a star.",
      steps: ["Drag \"points to\" to the little square at the end of the rule", "Put the eyes next to the score", "Crash into both stars and watch the score"],
      praise: "Crashing does not set a number: it swaps the rule \"score → 0\" for \"score → 1\", and so on. It adds one every time.",
    },
    "add-zero": {
      title: "Zero plus a number",
      mission: "Represent the sum of zero and a number.",
      steps: ["Put the eyes next to the 2 at the top", "Now drag the idea of \"number\" to the square at the end"],
      praise: "Zero plus a number is that number. Addition starts with that rule: the base case.",
    },
    "build-chess": {
      title: "Chess",
      mission: "Tap the pencil and draw a black piece",
      steps: ["Tap the pencil and draw a black piece", "Now draw a white piece", "Put a black piece and a white piece on the board", "Make the rule: black piece · arrows", "Make the eating rule: black · bumps · white · turns into · white · teleport · black hole", "Eat the white piece"],
      praise: "You built a tiny chess: your pieces, your rules. The real one adds categories: \"black piece\" for all the black ones.",
    },
  },
};
