// Los textos del tutorial en es. Generado a partir de la versión original;
// para agregar un idioma, copiar este archivo y traducir los valores.
export const es = {
  ui: {
    "nav.play": "Secuencia",
    "nav.home": "Inicio",
    "nav.mine": "Míos",
    "nav.badges": "Logros",
    "nav.create": "Crear",
    "mine.title": "Míos",
    "mine.projects": "proyectos",
    "mine.badges": "logros",
    "badges.title": "Logros",
    "app.title": "Introducción a Diálogo",
    "play.title": "Una introducción jugando",
    "play.subtitle": "Una introducción divertida para jugar, conocer los simbolos básicos y después poder bajar Diálogo en tu computadora y hacer los proyectos.",
    "play.goal": "Objetivo",
    "play.previous": "Nivel anterior",
    "play.redo": "Jugarlo de nuevo",
    "play.next": "Próximo desafío",
    "play.locked": "Terminá los desafíos para destrabar",
    "play.builds": "Armá tus propios juegos",
    "play.free": "Creación libre",
    "play.startOver": "Empezar de cero",
    "play.startOverConfirm": "¿Empezar de cero? Se borran tus desafíos y medallas.",
    "play.freeHint": "Se destraba cuando termines de armar los juegos",
    "language": "Idioma",
    "sound": "Sonido",
    "sound.on": "Sonido: sí",
    "sound.off": "Sonido: no",
    "openFile": "Abrir un archivo .dialog.ar",
    "more": "Más",
    "open": "Abrir",
    "copyAndChange": "Copiar y cambiar",
    "download": "Descargar .dialog.ar",
    "myVersionOf": "Mi versión de",
    "mineSuffix": "(mío)",
    "error.open": "No se pudo abrir el proyecto",
    "error.copy": "No se pudo copiar el proyecto",
    "error.file": "No se pudo abrir el archivo",
    "error.openNamed": "No se pudo abrir:",
    "feed.challenge": "Desafío",
    "feed.nextChallenge": "Tu próximo desafío",
    "feed.play": "Jugar",
    "feed.live": "en vivo",
    "feed.you": "Vos",
    "feed.empty": "Creá tu primer proyecto",
    "feed.watchOnly": "Este proyecto se mira, no se maneja",
    "category.games": "Juego",
    "category.didactic": "Didáctico",
    "category.mine": "Mío",
    "success.title": "¡Lo lograste!",
    "success.next": "Siguiente",
    "success.home": "Al inicio",
    "success.stay": "Quedarme a inventar",
    "success.yours": "Ahora es tuyo. Cambiá lo que quieras. Lo vas a encontrar en Míos.",
    "menu.backToStart": "Volver al inicio",
    "menu.forBuilding": "Para armar",
    "menu.setStart": "Fijar este inicio",
    "menu.reuse": "Usar fichas de otros proyectos",
    "challenge.restart": "Volver a empezar",
    "tray.draw": "Dibujar",
    "tray.drawing": "Dibujo",
    "tray.symbol": "Ficha",
    "joystick.space": "Espacio",
    "joystick.enter": "Enter",
    "paint.title": "Dibujar",
    "paint.done": "Listo",
    "paint.close": "Cerrar sin guardar",
    "paint.brush": "Pincel",
    "paint.eraser": "Goma",
    "paint.bucket": "Balde",
    "paint.undo": "Deshacer",
    "paint.size": "Grosor",
    "paint.canvas": "Lienzo",
    "color.black": "Negro",
    "color.orange": "Naranja",
    "color.blue": "Azul",
    "color.brown": "Marrón",
    "badge.first-drop": "Primera ficha|Poné una ficha en el tablero",
    "badge.rule": "Primera regla|Armá una regla con fichas",
    "badge.first-move": "En movimiento|Movete por primera vez",
    "badge.artist": "Dibujante|Dibujá una ficha nueva",
    "badge.detective": "Detective|Usá los ojitos para ver qué dice una regla",
    "badge.explorer": "Explorador|Abrí tres proyectos",
    "badge.remix": "Inventor|Copiá un proyecto y cambialo",
    "badge.saver": "Coleccionista|Guardá un proyecto tuyo",
    "badge.world": "Mundo completo|Terminá todos los desafíos de un mundo",
    "badge.ladder": "Campeón|Terminá todos los desafíos",
    "end.title": "¡Felicitaciones!",
    "end.text": "Ya entendiste los básico del Diálogo. Podés seguir con los proyectos, a través de los videotutoriales. El próximo paso es descargar Diálogo y luego el primer proyecto de Ajedrez.",
    "end.note": "Diálogo se instala en una computadora: desde el celular no vas a poder seguir.",
    "end.download": "Bajar Diálogo en la computadora",
    "end.watch": "Clase 1: Ajedrez (video)",
    "end.later": "Ahora no",
    "color.white": "Blanco",
    "color.red": "Rojo",
    "color.yellow": "Amarillo",
    "color.green": "Verde",
    "color.purple": "Violeta",
    "color.pink": "Rosa",
    "color.cyan": "Celeste",
    "color.gray": "Gris",
    "world.primeros": "Primeros pasos",
    "world.choques": "Choques",
    "world.categorias": "Categorías",
    "world.sustitucion": "Sustitución",
    "world.metaprogramacion": "Reglas que cambian",
    "world.naves": "Naves y tiempo",
    "world.numeros": "Números",
    "world.puntos": "Puntos",
    "world.builds": "Armá tus propios juegos",
  },
  challenges: {
    "reach-star": {
      title: "Viaje a las estrellas",
      mission: "Llevá al personaje hasta la estrella.",
      steps: ["Mové el personaje con las flechas"],
      praise: "El simbolo del personaje está al lado del de las flechas: por eso se mueve.",
    },
    "make-rule": {
      title: "Armá tu primera regla",
      mission: "Llevá al personaje hasta la estrella.",
      steps: ["Arrastrá las flechas al lado del simbolo del personaje", "¡Se puede mover! Llevalo a la estrella"],
      praise: "Personaje + flechas = se mueve. Eso es una regla.",
    },
    "eat-star": {
      title: "Comé las estrellas",
      mission: "Que el personaje borre del tablero todas las estrellas.",
      steps: ["Arrastrá el agujero negro y completá la regla", "Ahora movete a las dos estrellas"],
      praise: "Cuando el personaje choca una estrella, la estrella se va al agujero negro: desaparece para siempre.",
    },
    "draw": {
      title: "Dibujá",
      mission: "Dibujá tu propio personaje.",
      steps: ["Tocá el lápiz. Dibujá."],
      praise: "Tu dibujo ya es un personaje. Ahora vamos a hacer que se mueva.",
    },
    "bring-to-life": {
      title: "Dale vida a tu personaje",
      mission: "Llevar tu personaje hasta la estrella.",
      steps: ["Arrastrá el simbolo de tu personaje al lado del de las flechas", "¡Tu personaje se puede mover! Llevalo hasta la estrella"],
      praise: "Tu dibujo + flechas = tu dibujo se mueve. Vos armaste esa regla.",
    },
    "run": {
      title: "El monstruo corre",
      mission: "Que el monstruo vaya solo hasta la estrella.",
      steps: ["Coloca «corre hacia» entre el simbolo del monstruo y el de la estrella", "Mirá: el monstruo corre solo"],
      praise: "Monstruo + corre hacia + estrella: el monstruo va solo hasta la estrella, sin que toques nada.",
    },
    "push": {
      title: "Correo espacial",
      mission: "Llevá el paquete hasta la estrella.",
      steps: ["Arrastrá «empuja» entre el simbolo del personaje y el de la caja", "Movete con las flechas y empujá la caja hasta la estrella"],
      praise: "Personaje + empuja + caja: el personaje puede empujar cajas.",
    },
    "walls": {
      title: "Definí los límites del movimiento",
      mission: "Que el monstruo quede del otro lado de la pared.",
      steps: ["Arrastrá «no puede pasar» entre el símbolo del monstruo y el de la pared", "Mirá qué hace el monstruo"],
      praise: "Monstruo + no puede pasar + pared: el monstruo no puede atravesar paredes.",
    },
    "eyes": {
      title: "Los ojos",
      mission: "Mirá lo que dice una regla, sin jugar.",
      steps: ["Arrastrá los ojitos hasta el cuadradito, al lado de la estrella"],
      praise: "Los ojitos muestran lo que dice la regla: acá, la estrella se hace corazón.",
    },
    "sun": {
      title: "Sale el sol",
      mission: "Hacé que el sol salga sobre las nubes.",
      steps: ["Arrastrá «teletransportar» entre el símbolo del sol y el de la nube", "Mové la oveja hasta el pasto"],
      praise: "Cuando la oveja choca el pasto, el sol aparece en la nube. Una colisión puede hacer aparecer cosas.",
    },
    "eat-all": {
      title: "Comé mucha fruta y también estrellas",
      mission: "Que el personaje desaparezca a todas las manzanas y estrellas.",
      steps: ["Arrastrá el agujero negro donde corresponde", "Ahora avanzá sobre las manzanas y las estrellas"],
      praise: "Una regla por cada cosa que se come. Con dos reglas, el personaje come dos cosas.",
    },
    "portal": {
      title: "El portal",
      mission: "Teleportate al otro lado de la pared y llegá a la estrella.",
      steps: ["Arrastrá «teletransportar» entre el símbolo del personaje y el de la puerta", "Entrá al portal y alcanzá a la estrella"],
      praise: "Personaje choca portal → el personaje aparece en la puerta. Así se teleporta un personaje.",
    },
    "pull": {
      title: "Tirar de cosas",
      mission: "Llevate la caja con vos hasta la estrella.",
      steps: ["Arrastrá «tira de» entre el simbolo del personaje y el de la caja", "Llevá al personaje hasta la estrella. La caja lo sigue"],
      praise: "Personaje + tira de + caja: la caja va detrás del personaje.",
    },
    "nobody-passes": {
      title: "Nadie pasa",
      mission: "Dejá al fantasma atrapado y llegá a la estrella.",
      steps: ["Arrastrá el comodín junto al «no puede pasar»", "Llevá al personaje hasta la estrella. El fantasma no lo puede alcanzar"],
      praise: "El comodín vale por cualquier cosa: ningún personaje puede atravesar la pared, ni el fantasma ni vos.",
    },
    "food": {
      title: "Una dieta balanceada",
      mission: "Que el personaje coma manzanas y pescado.",
      steps: ["Arrastrá «está dentro de» entre el símbolo del pescado y el de comida", "Ahora comé todo"],
      praise: "La manzana está dentro de la idea de comida, el pescado también: una sola regla permite a comer comidas diferentes. Eso es una categoría.",
    },
    "one-rule": {
      title: "Una regla para muchos objetos",
      mission: "Comé tres cosas distintas por medio de una sola regla.",
      steps: ["Arrastrá el simbolo «comida» y completa la regla", "Ahora comé todo"],
      praise: "Tres cosas distintas, una sola regla: la regla habla de la categoría abstracta, y no de cada cosa concreta.",
    },
    "day-night": {
      title: "Del día viene noche",
      mission: "Convertí el sol en luna.",
      steps: ["Arrastrá «se transforma en» entre el símbolo del sol y el de la luna", "Ahora poné los ojitos al lado del símbolo del sol, que está más arriba"],
      praise: "Sol → luna: el sol se convierte en luna. Eso es una regla de sustitución de un símbolo por otro.",
    },
    "chain": {
      title: "Transformación en cadena",
      mission: "Convertí el sol en estrella, paso a paso.",
      steps: ["Arrastrá «se transforma en» entre el simbolo de la luna y el de la la estrella", "Ahora poné los ojitos al lado del simbolo del sol de arriba"],
      praise: "Sol → luna → estrella: las sustituciones se encadenan hasta el final.",
    },
    "break-rule": {
      title: "Borrá la regla jugando",
      mission: "Rompé tu propia regla para poder cruzar la pared.",
      steps: ["Empujá algún simbolo de la regla que te impide atravesar la pared", "Ahora atravesá la pared hasta la estrella"],
      praise: "El personaje puede modificar reglas. El juego cambia sus propias reglas mientras jugás.",
    },
    "rule-by-playing": {
      title: "Creá la regla jugando",
      mission: "Armá una regla empujando símbolos y llegá a la estrella.",
      steps: ["Empujá «tira de» entre los dos símbolos sueltos", "Ahora llevá al personaje hasta la caja y pasá por arriba de la estrella. La caja lo sigue"],
      praise: "Armaste una regla sin sacar fichas de abajo: empujando símbolos por el tablero.",
    },
    "fire": {
      title: "Flechazo",
      mission: "Clavale un flechazo al fantasma.",
      steps: ["Arrastrá «corre hacia» hasta el cuadradito, entre la flecha y el fantasma", "Tocá la barra de espacio"],
      praise: "La barra hace aparecer la flecha en la nave, y la flecha corre hacia el fantasma. Dos reglas, un flechazo.",
    },
    "missile": {
      title: "Que desaparezca",
      mission: "Derribá al fantasma con un flechazo.",
      steps: ["Arrastrá el agujero negro hasta el cuadradito del final de la regla de arriba", "Tocá la barra espaciadora"],
      praise: "Cuando la flecha choca al fantasma, el fantasma se va al agujero negro. Desaparece para siempre.",
    },
    "next": {
      title: "El número siguiente",
      mission: "Relacioná los numeros.",
      steps: ["Poné los ojitos al lado del 2 de arriba", "Ahora arrastrá el 3 hasta el cuadradito, ya que el siguiente de 2 es el 3"],
      praise: "No hay números en Diálogo: los inventás vos. «Siguiente de 2 → 3» es una regla como cualquier otra.",
    },
    "score": {
      title: "Puntos",
      mission: "Hacé que los puntos suban cuando tocása una estrella.",
      steps: ["Arrastrá «apunta a» hasta el cuadradito del final de la regla", "Poné los ojitos al lado de los puntos", "Chocá las dos veces las estrellas y mirá los puntos"],
      praise: "Chocar no pone un número: cambia la regla «puntos → 0» por «puntos → 1» y así. Suma uno cada vez.",
    },
    "add-zero": {
      title: "Cero más un número",
      mission: "Representá la suma de cero y un número.",
      steps: ["Poné los ojitos al lado del 2 de arriba", "Ahora arrastrá la idea de «número» hasta el cuadradito del final de la regla"],
      praise: "Cero más un número es ese número. Con esa regla empieza la suma: es el caso base.",
    },
    "build-chess": {
      title: "Ajedrez",
      mission: "Tocá el lápiz y dibujá una pieza negra",
      steps: ["Tocá el lápiz y dibujá una pieza negra", "Ahora dibujá una pieza blanca", "Poné una pieza negra y una blanca en el tablero", "Armá la regla: pieza negra · flechas", "Armá la regla de comer: negra · choca · blanca · se transforma en · blanca · teletransportar · agujero negro", "Comé la pieza blanca"],
      praise: "Armaste un ajedrez chiquito: tus piezas, tus reglas. El de verdad agrega categorías: «pieza negra» para todas las negras.",
    },
  },
};
