// Los textos del tutorial en es. Generado a partir de la versión original;
// para agregar un idioma, copiar este archivo y traducir los valores.
export const es = {
  ui: {
    "nav.play": "Tutorial",
    "nav.home": "Inicio",
    "nav.mine": "Míos",
    "nav.badges": "Logros",
    "nav.create": "Crear",
    "mine.title": "Míos",
    "mine.projects": "proyectos",
    "mine.badges": "logros",
    "badges.title": "Logros",
    "app.title": "Introducción a Diálogo",
    "play.title": "Introducción a Diálogo",
    "play.subtitle": "Un tutorial para empezar: jugá, aprendé las reglas y después bajá Diálogo.",
    "play.goal": "Objetivo",
    "play.previous": "Nivel anterior",
    "play.redo": "Jugarlo de nuevo",
    "play.next": "Próximo desafío",
    "play.locked": "Terminá los desafíos para destrabar",
    "play.builds": "Armá tus propios juegos",
    "play.free": "Creación libre",
    "play.startOver": "Empezar de cero",
    "play.startOverConfirm": "¿Empezar de cero? Se borran tus desafíos y medallas. Tus proyectos quedan.",
    "play.freeHint": "Se destraba cuando termines de armar los juegos",
    "language": "Idioma",
    "sound": "Sonido",
    "sound.on": "Sonido: sí",
    "sound.off": "Sonido: no",
    "openFile": "Abrir un archivo .dialog.ar",
    "more": "Más",
    "open": "Abrir",
    "copyAndChange": "Copiar y cambiar",
    "download": "Descargar .dialog.ar",
    "myVersionOf": "Mi versión de ",
    "mineSuffix": " (mío)",
    "error.open": "No se pudo abrir el proyecto",
    "error.copy": "No se pudo copiar el proyecto",
    "error.file": "No se pudo abrir el archivo",
    "error.openNamed": "No se pudo abrir: ",
    "feed.challenge": "Desafío",
    "feed.nextChallenge": "Tu próximo desafío",
    "feed.play": "Jugar",
    "feed.live": "en vivo",
    "feed.you": "Vos",
    "feed.empty": "Creá tu primer proyecto",
    "feed.watchOnly": "Este proyecto se mira, no se maneja",
    "category.games": "Juego",
    "category.didactic": "Didáctico",
    "category.mine": "Mío",
    "success.title": "¡Lo lograste!",
    "success.next": "Siguiente",
    "success.home": "Al inicio",
    "success.stay": "Quedarme a inventar",
    "success.yours": "Ahora es tuyo. Cambiá lo que quieras. Lo vas a encontrar en Míos.",
    "menu.backToStart": "Volver al inicio",
    "menu.forBuilding": "Para armar",
    "menu.setStart": "Fijar este inicio",
    "menu.reuse": "Usar fichas de otros proyectos",
    "challenge.restart": "Volver a empezar",
    "tray.draw": "Dibujar",
    "tray.drawing": "Dibujo",
    "tray.symbol": "Ficha",
    "joystick.space": "Espacio",
    "joystick.enter": "Enter",
    "paint.title": "Dibujar",
    "paint.done": "Listo",
    "paint.close": "Cerrar sin guardar",
    "paint.brush": "Pincel",
    "paint.eraser": "Goma",
    "paint.bucket": "Balde",
    "paint.undo": "Deshacer",
    "paint.size": "Grosor",
    "paint.canvas": "Lienzo",
    "color.black": "Negro",
    "color.orange": "Naranja",
    "color.blue": "Azul",
    "color.brown": "Marrón",
    "badge.first-drop": "Primera ficha|Poné una ficha en el tablero",
    "badge.rule": "Primera regla|Armá una regla con fichas",
    "badge.first-move": "En movimiento|Movete por primera vez",
    "badge.artist": "Dibujante|Dibujá una ficha nueva",
    "badge.detective": "Detective|Usá los ojitos para ver qué dice una regla",
    "badge.explorer": "Explorador|Abrí tres proyectos",
    "badge.remix": "Inventor|Copiá un proyecto y cambialo",
    "badge.saver": "Coleccionista|Guardá un proyecto tuyo",
    "badge.world": "Mundo completo|Terminá todos los desafíos de un mundo",
    "badge.ladder": "Campeón|Terminá todos los desafíos",
    "end.title": "¡Excelente!",
    "end.text": "Completaste el tutorial web. Te invitamos a bajar el ambiente desde dialog.ar y hacer el primer proyecto de ajedrez con tus dibujos.",
    "end.download": "Bajar Diálogo",
    "end.watch": "Clase 1: Ajedrez (video)",
    "end.later": "Ahora no",
    "color.white": "Blanco",
    "color.red": "Rojo",
    "color.yellow": "Amarillo",
    "color.green": "Verde",
    "color.purple": "Violeta",
    "color.pink": "Rosa",
    "color.cyan": "Celeste",
    "color.gray": "Gris",
    "world.primeros": "Primeros pasos",
    "world.choques": "Choques",
    "world.categorias": "Categorías",
    "world.sustitucion": "Sustitución",
    "world.metaprogramacion": "Reglas que cambian",
    "world.naves": "Naves y tiempo",
    "world.numeros": "Números",
    "world.puntos": "Puntos",
    "world.builds": "Armá tus propios juegos",
  },
  challenges: {
    "reach-star": {
      title: "Llegá a la estrella",
      mission: "Llevá al personaje hasta la estrella.",
      steps: ["Llevá al personaje hasta la estrella con las flechas"],
      praise: "El personaje está al lado de las flechas: por eso se mueve.",
    },
    "make-rule": {
      title: "Armá la regla",
      mission: "Hacé que el personaje se mueva y llegue a la estrella.",
      steps: ["Arrastrá las flechas hasta el cuadradito, al lado del personaje", "¡Ahora se mueve! Llevalo hasta la estrella"],
      praise: "Personaje + flechas = se mueve. Eso es una regla.",
    },
    "eat-star": {
      title: "Comé las estrellas",
      mission: "Que el personaje saque del tablero todas las estrellas.",
      steps: ["Arrastrá el agujero negro hasta el cuadradito del final de la regla", "Ahora chocá las dos estrellas"],
      praise: "Cuando el personaje choca una estrella, la estrella se va al agujero negro: desaparece para siempre.",
    },
    "draw": {
      title: "Dibujá",
      mission: "Dibujá tu propio personaje.",
      steps: ["Tocá el lápiz. Dibujá tu personaje"],
      praise: "Tu dibujo ya es un personaje. Ahora vamos a hacer que se mueva.",
    },
    "bring-to-life": {
      title: "Dale vida",
      mission: "Dale vida a tu dibujo y llevalo hasta la estrella.",
      steps: ["Arrastrá tu dibujo hasta el cuadradito, al lado de las flechas", "¡Tu dibujo se mueve! Llevalo hasta la estrella"],
      praise: "Tu dibujo + flechas = tu dibujo se mueve. Vos armaste esa regla.",
    },
    "run": {
      title: "El monstruo corre",
      mission: "Que el monstruo llegue solo hasta la estrella.",
      steps: ["Arrastrá «corre hacia» hasta el cuadradito, entre el monstruo y la estrella", "Mirá: el monstruo corre solo"],
      praise: "Monstruo + corre hacia + estrella: el monstruo va solo hasta la estrella, sin que toques nada.",
    },
    "push": {
      title: "Empujá la caja",
      mission: "Llevá la caja hasta la estrella.",
      steps: ["Arrastrá «empuja» hasta el cuadradito, entre el personaje y la caja", "Ahora empujá la caja hasta la estrella"],
      praise: "Personaje + empuja + caja: cuando el personaje choca la caja, la caja se mueve.",
    },
    "walls": {
      title: "La pared",
      mission: "Frená al monstruo con la pared para que no te alcance.",
      steps: ["Arrastrá «no puede pasar» hasta el cuadradito, entre el monstruo y la pared", "Mirá qué hace el monstruo"],
      praise: "Monstruo + no puede pasar + pared: el monstruo corre, pero la pared lo frena.",
    },
    "eyes": {
      title: "Los ojos",
      mission: "Mirá lo que dice una regla, sin jugar.",
      steps: ["Arrastrá los ojitos hasta el cuadradito, al lado de la estrella"],
      praise: "Los ojitos muestran lo que dice la regla: acá, la estrella se hace corazón.",
    },
    "sun": {
      title: "Sale el sol",
      mission: "Hacé que el sol salga sobre las nubes.",
      steps: ["Arrastrá «teletransportar» hasta el cuadradito, entre el sol y la nube", "Llevá la oveja hasta el pasto"],
      praise: "Cuando la oveja choca el pasto, el sol aparece en la nube. Un choque puede hacer aparecer cosas.",
    },
    "eat-all": {
      title: "Comé todo",
      mission: "Que el personaje saque del tablero todas las manzanas y estrellas.",
      steps: ["Arrastrá el agujero negro hasta el cuadradito", "Ahora comé las manzanas y las estrellas"],
      praise: "Una regla por cada cosa que se come. Con dos reglas, el personaje come dos cosas.",
    },
    "portal": {
      title: "El portal",
      mission: "Cruzá la pared y llegá a la estrella.",
      steps: ["Arrastrá «teletransportar» hasta el cuadradito, entre el personaje y la puerta", "Entrá al portal y llegá a la estrella"],
      praise: "Personaje choca portal → el personaje aparece en la puerta. Así se cruza una pared.",
    },
    "pull": {
      title: "Tirá de la caja",
      mission: "Llevate la caja con vos hasta la estrella.",
      steps: ["Arrastrá «tira de» hasta el cuadradito, entre el personaje y la caja", "Llevá al personaje hasta la estrella. La caja lo sigue"],
      praise: "Personaje + tira de + caja: la caja va detrás del personaje.",
    },
    "nobody-passes": {
      title: "Nadie pasa",
      mission: "Dejá al fantasma afuera y llegá a la estrella.",
      steps: ["Arrastrá el comodín hasta el cuadradito, antes de «no puede pasar»", "Llevá al personaje hasta la estrella. El fantasma no pasa"],
      praise: "El comodín vale por cualquier cosa: nadie pasa la pared, ni el fantasma ni vos.",
    },
    "food": {
      title: "Todo es comida",
      mission: "Que el personaje coma manzanas y pescado: una dieta balanceada.",
      steps: ["Arrastrá «está dentro de» hasta el cuadradito, entre el pescado y la comida", "Ahora comé todo"],
      praise: "La manzana está dentro de comida, el pescado también: una sola regla come las dos. Eso es una categoría.",
    },
    "one-rule": {
      title: "Una regla para todo",
      mission: "Comé tres cosas distintas con una sola regla.",
      steps: ["Arrastrá «comida» hasta los dos cuadraditos de la regla", "Ahora comé todo"],
      praise: "Tres cosas distintas, una sola regla: la regla habla de la categoría, no de cada cosa.",
    },
    "day-night": {
      title: "Día y noche",
      mission: "Convertí el sol en luna.",
      steps: ["Arrastrá «se transforma en» hasta el cuadradito, entre el sol y la luna", "Ahora poné los ojitos al lado del sol de arriba"],
      praise: "Sol → luna: el sol se convierte en luna. Eso es una sustitución.",
    },
    "chain": {
      title: "En cadena",
      mission: "Convertí el sol en estrella, paso a paso.",
      steps: ["Arrastrá «se transforma en» hasta el cuadradito, entre la luna y la estrella", "Ahora poné los ojitos al lado del sol de arriba"],
      praise: "Sol → luna → estrella: las sustituciones se encadenan hasta el final.",
    },
    "break-rule": {
      title: "Rompé la regla",
      mission: "Rompé tu propia regla para cruzar la pared.",
      steps: ["Empujá «no puede pasar» para afuera de la regla", "Ahora atravesá la pared hasta la estrella"],
      praise: "Empujaste un pedazo de tu programa. El juego cambia sus propias reglas mientras jugás.",
    },
    "rule-by-playing": {
      title: "Armá la regla jugando",
      mission: "Armá una regla empujando sus piezas y llegá a la estrella.",
      steps: ["Empujá «tira de» hasta el cuadradito de la regla", "Ahora llevá al personaje hasta la estrella. La caja lo sigue"],
      praise: "Armaste una regla sin la bandeja: empujando sus piezas por el tablero.",
    },
    "fire": {
      title: "Flechazo",
      mission: "Clavale un flechazo al fantasma.",
      steps: ["Arrastrá «corre hacia» hasta el cuadradito, entre la flecha y el fantasma", "Tocá la barra de espacio"],
      praise: "La barra hace aparecer la flecha en la nave, y la flecha corre hacia el fantasma. Dos reglas, un flechazo.",
    },
    "missile": {
      title: "Que desaparezca",
      mission: "Derribá al fantasma para que desaparezca.",
      steps: ["Arrastrá el agujero negro hasta el cuadradito del final de la regla de arriba", "Tocá la barra de espacio"],
      praise: "Una regla más: cuando la flecha choca al fantasma, el fantasma se va al agujero negro. Desaparece para siempre.",
    },
    "next": {
      title: "El siguiente",
      mission: "Inventá el número 3.",
      steps: ["Poné los ojitos al lado del 2 de arriba", "Ahora arrastrá el 3 hasta el cuadradito: el siguiente de 2 es 3"],
      praise: "No hay números en Diálogo: los inventás vos. «Siguiente de 2 → 3» es una regla como cualquier otra.",
    },
    "score": {
      title: "Puntos",
      mission: "Hacé que los puntos suban cuando comés una estrella.",
      steps: ["Arrastrá «apunta a» hasta el cuadradito del final de la regla", "Poné los ojitos al lado de los puntos", "Chocá las dos estrellas y mirá los puntos"],
      praise: "Chocar no pone un número: cambia la regla «puntos → 0» por «puntos → el siguiente». Suma uno cada vez. Sin variables.",
    },
    "add-zero": {
      title: "Sumar cero",
      mission: "Enseñale a Diálogo a sumar cero.",
      steps: ["Poné los ojitos al lado del 2 de arriba", "Ahora arrastrá «número» hasta el cuadradito del final de la regla"],
      praise: "Cero más un número es ese número. Con esa regla empieza la suma: es el caso base.",
    },
    "build-chess": {
      title: "Ajedrez",
      mission: "Tocá el lápiz y dibujá una pieza negra",
      steps: ["Tocá el lápiz y dibujá una pieza negra", "Ahora dibujá una pieza blanca", "Poné una pieza negra y una blanca en el tablero", "Armá la regla: pieza negra · flechas", "Armá la regla de comer: negra · choca · blanca · se transforma en · blanca · teletransportar · agujero negro", "Comé la pieza blanca"],
      praise: "Armaste un ajedrez chiquito: tus piezas, tus reglas. El de verdad agrega categorías: «pieza negra» para todas las negras.",
    },
  },
};
