// Les textes du tutoriel en français. Un verbe par phrase, nommer ce qui se voit.
export const fr = {
  ui: {
    "nav.play": "Tutoriel",
    "nav.home": "Accueil",
    "nav.mine": "À moi",
    "nav.badges": "Badges",
    "nav.create": "Créer",
    "mine.title": "À moi",
    "mine.projects": "projets",
    "mine.badges": "badges",
    "badges.title": "Badges",
    "app.title": "Introduction à Diálogo",
    "play.title": "Introduction à Diálogo",
    "play.subtitle": "Un tutoriel pour commencer : joue, apprends les règles, puis télécharge Diálogo.",
    "play.goal": "But",
    "play.previous": "Niveau précédent",
    "play.redo": "Rejouer",
    "play.next": "Prochain défi",
    "play.locked": "Termine les défis pour débloquer",
    "play.builds": "Construis tes propres jeux",
    "play.free": "Création libre",
    "play.startOver": "Tout recommencer",
    "play.startOverConfirm": "Tout recommencer ? Tes défis et tes badges seront effacés. Tes projets restent.",
    "play.freeHint": "Se débloque quand tu finis de construire les jeux",
    "language": "Langue",
    "sound": "Son",
    "sound.on": "Son : oui",
    "sound.off": "Son : non",
    "openFile": "Ouvrir un fichier .dialog.ar",
    "more": "Plus",
    "open": "Ouvrir",
    "copyAndChange": "Copier et changer",
    "download": "Télécharger .dialog.ar",
    "myVersionOf": "Ma version de ",
    "mineSuffix": " (à moi)",
    "error.open": "Impossible d'ouvrir le projet",
    "error.copy": "Impossible de copier le projet",
    "error.file": "Impossible d'ouvrir le fichier",
    "error.openNamed": "Impossible d'ouvrir : ",
    "feed.challenge": "Défi",
    "feed.nextChallenge": "Ton prochain défi",
    "feed.play": "Jouer",
    "feed.live": "en direct",
    "feed.you": "Toi",
    "feed.empty": "Crée ton premier projet",
    "feed.watchOnly": "Ce projet se regarde, il ne se pilote pas",
    "category.games": "Jeu",
    "category.didactic": "Leçon",
    "category.mine": "À moi",
    "success.title": "Tu as réussi !",
    "success.next": "Suivant",
    "success.home": "Accueil",
    "success.stay": "Rester et inventer",
    "success.yours": "C'est à toi. Change ce que tu veux. Tu le retrouveras dans « À moi ».",
    "menu.backToStart": "Revenir au début",
    "menu.forBuilding": "Pour construire",
    "menu.setStart": "Fixer ce début",
    "menu.reuse": "Utiliser des tuiles d'autres projets",
    "challenge.restart": "Recommencer",
    "tray.draw": "Dessiner",
    "tray.drawing": "Dessin",
    "tray.symbol": "Tuile",
    "joystick.space": "Espace",
    "joystick.enter": "Entrée",
    "paint.title": "Dessiner",
    "paint.done": "Terminé",
    "paint.close": "Fermer sans garder",
    "paint.brush": "Pinceau",
    "paint.eraser": "Gomme",
    "paint.bucket": "Pot de peinture",
    "paint.undo": "Annuler",
    "paint.size": "Épaisseur",
    "paint.canvas": "Toile",
    "color.black": "Noir",
    "color.orange": "Orange",
    "color.blue": "Bleu",
    "color.brown": "Marron",
    "color.white": "Blanc",
    "color.red": "Rouge",
    "color.yellow": "Jaune",
    "color.green": "Vert",
    "color.purple": "Violet",
    "color.pink": "Rose",
    "color.cyan": "Bleu ciel",
    "color.gray": "Gris",
    "badge.first-drop": "Première tuile|Pose une tuile sur le plateau",
    "badge.rule": "Première règle|Fais une règle avec des tuiles",
    "badge.first-move": "En mouvement|Déplace le personnage pour la première fois",
    "badge.artist": "Dessinateur|Dessine une nouvelle tuile",
    "badge.detective": "Détective|Utilise les yeux pour voir ce que dit une règle",
    "badge.explorer": "Explorateur|Ouvre trois projets",
    "badge.remix": "Inventeur|Copie un projet et change-le",
    "badge.saver": "Collectionneur|Garde un projet à toi",
    "badge.world": "Monde terminé|Finis tous les défis d'un monde",
    "badge.ladder": "Champion|Finis tous les défis",
    "end.title": "Excellent !",
    "end.text": "Tu as terminé le tutoriel web. Télécharge maintenant l'environnement sur dialog.ar et fais ton premier projet d'échecs avec tes propres dessins.",
    "end.download": "Télécharger Diálogo",
    "end.watch": "Cours 1 : Échecs (vidéo)",
    "end.later": "Pas maintenant",
    "world.primeros": "Premiers pas",
    "world.choques": "Chocs",
    "world.categorias": "Catégories",
    "world.sustitucion": "Substitution",
    "world.metaprogramacion": "Règles qui changent",
    "world.naves": "Vaisseaux et temps",
    "world.numeros": "Nombres",
    "world.puntos": "Points",
    "world.builds": "Construis tes propres jeux",
  },
  challenges: {
    "reach-star": {
      title: "Atteins l'étoile",
      mission: "Amène le personnage jusqu'à l'étoile.",
      steps: ["Amène le personnage jusqu'à l'étoile avec les flèches"],
      praise: "Le personnage est à côté des flèches : c'est pour ça qu'il bouge.",
    },
    "make-rule": {
      title: "Fais la règle",
      mission: "Fais bouger le personnage, puis amène-le à l'étoile.",
      steps: ["Glisse les flèches dans la petite case, à côté du personnage", "Il bouge ! Amène-le jusqu'à l'étoile"],
      praise: "Personnage + flèches = il bouge. Ça, c'est une règle.",
    },
    "eat-star": {
      title: "Mange les étoiles",
      mission: "Fais disparaître toutes les étoiles du plateau.",
      steps: ["Glisse le trou noir dans la petite case au bout de la règle", "Maintenant, cogne les deux étoiles"],
      praise: "Quand le personnage cogne une étoile, l'étoile tombe dans le trou noir : elle disparaît pour de bon.",
    },
    "draw": {
      title: "Dessine",
      mission: "Dessine ton propre personnage.",
      steps: ["Touche le crayon. Dessine ton personnage"],
      praise: "Ton dessin est un personnage maintenant. Ensuite, on le fait bouger.",
    },
    "bring-to-life": {
      title: "Donne-lui vie",
      mission: "Donne vie à ton dessin et amène-le à l'étoile.",
      steps: ["Glisse ton dessin dans la petite case, à côté des flèches", "Ton dessin bouge ! Amène-le jusqu'à l'étoile"],
      praise: "Ton dessin + flèches = ton dessin bouge. Cette règle, c'est toi qui l'as faite.",
    },
    "run": {
      title: "Le monstre court",
      mission: "Fais que le monstre arrive tout seul à l'étoile.",
      steps: ["Glisse « court vers » dans la petite case, entre le monstre et l'étoile", "Regarde : le monstre court tout seul"],
      praise: "Monstre + court vers + étoile : le monstre va à l'étoile tout seul, sans que tu touches rien.",
    },
    "push": {
      title: "Pousse la caisse",
      mission: "Amène la caisse sur l'étoile.",
      steps: ["Glisse « pousse » dans la petite case, entre le personnage et la caisse", "Maintenant, pousse la caisse jusqu'à l'étoile"],
      praise: "Personnage + pousse + caisse : quand le personnage cogne la caisse, la caisse bouge.",
    },
    "walls": {
      title: "Le mur",
      mission: "Arrête le monstre avec le mur pour qu'il ne t'attrape pas.",
      steps: ["Glisse « ne passe pas » dans la petite case, entre le monstre et le mur", "Regarde ce que fait le monstre"],
      praise: "Monstre + ne passe pas + mur : le monstre court, mais le mur l'arrête.",
    },
    "eyes": {
      title: "Les yeux",
      mission: "Vois ce que dit une règle, sans jouer.",
      steps: ["Glisse les yeux dans la petite case, à côté de l'étoile"],
      praise: "Les yeux montrent ce que dit la règle : ici, l'étoile devient un cœur.",
    },
    "sun": {
      title: "Le soleil se lève",
      mission: "Fais sortir le soleil au-dessus des nuages.",
      steps: ["Glisse « téléporte » dans la petite case, entre le soleil et le nuage", "Amène le mouton jusqu'à l'herbe"],
      praise: "Quand le mouton cogne l'herbe, le soleil apparaît dans les nuages. Un choc peut faire apparaître des choses.",
    },
    "eat-all": {
      title: "Mange tout",
      mission: "Fais disparaître toutes les pommes et toutes les étoiles.",
      steps: ["Glisse le trou noir dans la petite case", "Maintenant, mange les pommes et les étoiles"],
      praise: "Une règle pour chaque chose à manger. Avec deux règles, le personnage mange deux choses.",
    },
    "portal": {
      title: "Le portail",
      mission: "Fais traverser le mur au personnage pour arriver à l'étoile.",
      steps: ["Glisse « téléporte » dans la petite case, entre le personnage et la porte", "Entre dans le portail et arrive à l'étoile"],
      praise: "Le personnage cogne le portail → le personnage apparaît à la porte. C'est comme ça qu'on traverse un mur.",
    },
    "pull": {
      title: "Tire la caisse",
      mission: "Emmène la caisse avec toi jusqu'à l'étoile.",
      steps: ["Glisse « tire » dans la petite case, entre le personnage et la caisse", "Amène le personnage à l'étoile. La caisse le suit"],
      praise: "Personnage + tire + caisse : la caisse va derrière le personnage.",
    },
    "nobody-passes": {
      title: "Personne ne passe",
      mission: "Laisse le fantôme dehors et arrive à l'étoile.",
      steps: ["Glisse le joker dans la petite case, avant « ne passe pas »", "Amène le personnage à l'étoile. Le fantôme ne passe pas"],
      praise: "Le joker vaut pour n'importe quoi : personne ne passe le mur, ni le fantôme, ni toi.",
    },
    "food": {
      title: "Tout est nourriture",
      mission: "Fais manger au personnage des pommes et du poisson : un repas équilibré.",
      steps: ["Glisse « est dans » dans la petite case, entre le poisson et la nourriture", "Maintenant, mange tout"],
      praise: "La pomme est dans la nourriture, le poisson aussi : une seule règle mange les deux. Ça, c'est une catégorie.",
    },
    "one-rule": {
      title: "Une règle pour tout",
      mission: "Mange trois choses différentes avec une seule règle.",
      steps: ["Glisse « nourriture » dans les deux petites cases de la règle", "Maintenant, mange tout"],
      praise: "Trois choses différentes, une seule règle : la règle parle de la catégorie, pas de chaque chose.",
    },
    "day-night": {
      title: "Jour et nuit",
      mission: "Transforme le soleil en lune.",
      steps: ["Glisse « se transforme en » dans la petite case, entre le soleil et la lune", "Mets les yeux à côté du soleil en haut"],
      praise: "Soleil → lune : le soleil se transforme en lune. Ça, c'est une substitution.",
    },
    "chain": {
      title: "En chaîne",
      mission: "Transforme le soleil en étoile, pas à pas.",
      steps: ["Glisse « se transforme en » dans la petite case, entre la lune et l'étoile", "Mets les yeux à côté du soleil en haut"],
      praise: "Soleil → lune → étoile : les substitutions s'enchaînent jusqu'au bout.",
    },
    "break-rule": {
      title: "Casse la règle",
      mission: "Casse ta propre règle pour traverser le mur.",
      steps: ["Pousse « ne passe pas » hors de la règle", "Maintenant, traverse le mur jusqu'à l'étoile"],
      praise: "Tu as poussé un morceau de ton programme. Le jeu change ses propres règles pendant que tu joues.",
    },
    "rule-by-playing": {
      title: "Fais une règle en jouant",
      mission: "Fais une règle en poussant ses pièces, puis arrive à l'étoile.",
      steps: ["Pousse « tire » dans la petite case de la règle", "Maintenant, amène le personnage à l'étoile. La caisse le suit"],
      praise: "Tu as fait une règle sans le plateau de tuiles : en poussant ses pièces sur le plateau.",
    },
    "fire": {
      title: "En plein dans le mille",
      mission: "Tire une flèche sur le fantôme.",
      steps: ["Glisse « court vers » dans la petite case, entre la flèche et le fantôme", "Appuie sur la barre d'espace"],
      praise: "La barre d'espace fait apparaître la flèche au vaisseau, et la flèche court vers le fantôme. Deux règles, un tir en plein dans le mille.",
    },
    "missile": {
      title: "Fais-le disparaître",
      mission: "Abats le fantôme pour qu'il disparaisse.",
      steps: ["Glisse le trou noir dans la petite case au bout de la règle du haut", "Appuie sur la barre d'espace"],
      praise: "Une règle de plus : quand la flèche cogne le fantôme, le fantôme tombe dans le trou noir. Il disparaît pour de bon.",
    },
    "next": {
      title: "Le suivant",
      mission: "Invente le nombre 3.",
      steps: ["Mets les yeux à côté du 2 en haut", "Maintenant, glisse le 3 dans la petite case : le suivant de 2, c'est 3"],
      praise: "Il n'y a pas de nombres dans Diálogo : c'est toi qui les inventes. « Suivant de 2 → 3 » est une règle comme une autre.",
    },
    "score": {
      title: "Points",
      mission: "Fais monter les points quand tu manges une étoile.",
      steps: ["Glisse « pointe vers » dans la petite case au bout de la règle", "Mets les yeux à côté des points", "Cogne les deux étoiles et regarde les points"],
      praise: "Cogner ne met pas un nombre : ça remplace la règle « points → 0 » par « points → le suivant ». Ça ajoute un à chaque fois. Sans variables.",
    },
    "add-zero": {
      title: "Ajouter zéro",
      mission: "Apprends à Diálogo à ajouter zéro.",
      steps: ["Mets les yeux à côté du 2 en haut", "Maintenant, glisse « nombre » dans la petite case au bout de la règle"],
      praise: "Zéro plus un nombre, c'est ce nombre. L'addition commence par cette règle : le cas de base.",
    },
    "build-chess": {
      title: "Échecs",
      mission: "Touche le crayon et dessine une pièce noire",
      steps: ["Touche le crayon et dessine une pièce noire", "Dessine maintenant une pièce blanche", "Pose une pièce noire et une pièce blanche sur le plateau", "Fais la règle : pièce noire · flèches", "Fais la règle pour manger : noire · cogne · blanche · se transforme en · blanche · téléporte · trou noir", "Mange la pièce blanche"],
      praise: "Tu as construit un petit jeu d'échecs : tes pièces, tes règles. Le vrai ajoute des catégories : « pièce noire » pour toutes les noires.",
    },
  },
};
