// Les textes du tutoriel en français. Un verbe par phrase, nommer ce qui se voit.
export const fr = {
  ui: {
    "nav.play": "Parcours",
    "nav.home": "Accueil",
    "nav.mine": "À moi",
    "nav.badges": "Badges",
    "nav.create": "Créer",
    "mine.title": "À moi",
    "mine.projects": "projets",
    "mine.badges": "badges",
    "badges.title": "Badges",
    "app.title": "Introduction à Diálogo",
    "play.title": "Une introduction en jouant",
    "play.subtitle": "Une introduction amusante : joue, découvre les symboles de base, puis télécharge Diálogo sur ton ordinateur et fais les projets.",
    "play.goal": "But",
    "play.previous": "Niveau précédent",
    "play.redo": "Rejouer",
    "play.next": "Prochain défi",
    "play.locked": "Termine les défis pour débloquer",
    "play.builds": "Construis tes propres jeux",
    "play.free": "Création libre",
    "play.startOver": "Tout recommencer",
    "play.startOverConfirm": "Tout recommencer ? Tes défis et tes badges seront effacés.",
    "play.freeHint": "Se débloque quand tu finis de construire les jeux",
    "language": "Langue",
    "sound": "Son",
    "sound.on": "Son : oui",
    "sound.off": "Son : non",
    "openFile": "Ouvrir un fichier .dialog.ar",
    "more": "Plus",
    "open": "Ouvrir",
    "copyAndChange": "Copier et changer",
    "download": "Télécharger .dialog.ar",
    "myVersionOf": "Ma version de",
    "mineSuffix": "(à moi)",
    "error.open": "Impossible d'ouvrir le projet",
    "error.copy": "Impossible de copier le projet",
    "error.file": "Impossible d'ouvrir le fichier",
    "error.openNamed": "Impossible d'ouvrir :",
    "feed.challenge": "Défi",
    "feed.nextChallenge": "Ton prochain défi",
    "feed.play": "Jouer",
    "feed.live": "en direct",
    "feed.you": "Toi",
    "feed.empty": "Crée ton premier projet",
    "feed.watchOnly": "Ce projet se regarde, il ne se pilote pas",
    "category.games": "Jeu",
    "category.didactic": "Leçon",
    "category.mine": "À moi",
    "success.title": "Tu as réussi !",
    "success.next": "Suivant",
    "success.home": "Accueil",
    "success.stay": "Rester et inventer",
    "success.yours": "C'est à toi. Change ce que tu veux. Tu le retrouveras dans « À moi ».",
    "menu.backToStart": "Revenir au début",
    "menu.forBuilding": "Pour construire",
    "menu.setStart": "Fixer ce début",
    "menu.reuse": "Utiliser des tuiles d'autres projets",
    "challenge.restart": "Recommencer",
    "tray.draw": "Dessiner",
    "tray.drawing": "Dessin",
    "tray.symbol": "Tuile",
    "joystick.space": "Espace",
    "joystick.enter": "Entrée",
    "paint.title": "Dessiner",
    "paint.done": "Terminé",
    "paint.close": "Fermer sans garder",
    "paint.brush": "Pinceau",
    "paint.eraser": "Gomme",
    "paint.bucket": "Pot de peinture",
    "paint.undo": "Annuler",
    "paint.size": "Épaisseur",
    "paint.canvas": "Toile",
    "color.black": "Noir",
    "color.orange": "Orange",
    "color.blue": "Bleu",
    "color.brown": "Marron",
    "color.white": "Blanc",
    "color.red": "Rouge",
    "color.yellow": "Jaune",
    "color.green": "Vert",
    "color.purple": "Violet",
    "color.pink": "Rose",
    "color.cyan": "Bleu ciel",
    "color.gray": "Gris",
    "badge.first-drop": "Première tuile|Pose une tuile sur le plateau",
    "badge.rule": "Première règle|Fais une règle avec des tuiles",
    "badge.first-move": "En mouvement|Déplace le personnage pour la première fois",
    "badge.artist": "Dessinateur|Dessine une nouvelle tuile",
    "badge.detective": "Détective|Utilise les yeux pour voir ce que dit une règle",
    "badge.explorer": "Explorateur|Ouvre trois projets",
    "badge.remix": "Inventeur|Copie un projet et change-le",
    "badge.saver": "Collectionneur|Garde un projet à toi",
    "badge.world": "Monde terminé|Finis tous les défis d'un monde",
    "badge.ladder": "Champion|Finis tous les défis",
    "end.title": "Félicitations !",
    "end.text": "Tu comprends les bases de Diálogo. Tu peux continuer avec les projets grâce aux tutoriels vidéo. La prochaine étape : télécharger Diálogo, puis faire le premier projet d'échecs.",
    "end.note": "Diálogo s'installe sur un ordinateur : depuis le téléphone, tu ne pourras pas continuer.",
    "end.download": "Étape 2 : Télécharger Diálogo sur l'ordinateur",
    "end.watch": "Cours 1 : Échecs (vidéo)",
    "end.later": "Pas maintenant",
    "world.primeros": "Premiers pas",
    "world.choques": "Chocs",
    "world.categorias": "Catégories",
    "world.sustitucion": "Substitution",
    "world.metaprogramacion": "Règles qui changent",
    "world.naves": "Vaisseaux et temps",
    "world.numeros": "Nombres",
    "world.puntos": "Points",
    "world.builds": "Construis tes propres jeux",
  },
  challenges: {
    "reach-star": {
      title: "Voyage vers les étoiles",
      mission: "Amène le personnage jusqu'à l'étoile.",
      steps: ["Déplace le personnage avec les flèches"],
      praise: "Le symbole du personnage est à côté de celui des flèches : voilà pourquoi il bouge.",
    },
    "make-rule": {
      title: "Fais ta première règle",
      mission: "Amène le personnage jusqu'à l'étoile.",
      steps: ["Glisse les flèches à côté du symbole du personnage", "Il peut bouger ! Amène-le à l'étoile"],
      praise: "Personnage + flèches = il bouge. Ça, c'est une règle.",
    },
    "eat-star": {
      title: "Mange les étoiles",
      mission: "Que le personnage efface toutes les étoiles du plateau.",
      steps: ["Glisse le trou noir et complète la règle", "Passe maintenant sur les deux étoiles"],
      praise: "Quand le personnage cogne une étoile, l'étoile tombe dans le trou noir : elle disparaît pour de bon.",
    },
    "draw": {
      title: "Dessine",
      mission: "Dessine ton propre personnage.",
      steps: ["Touche le crayon. Dessine."],
      praise: "Ton dessin est un personnage maintenant. Ensuite, on le fait bouger.",
    },
    "bring-to-life": {
      title: "Donne vie à ton personnage",
      mission: "Amène ton personnage jusqu'à l'étoile.",
      steps: ["Glisse le symbole de ton personnage à côté de celui des flèches", "Ton personnage peut bouger ! Amène-le jusqu'à l'étoile"],
      praise: "Ton dessin + flèches = ton dessin bouge. Cette règle, c'est toi qui l'as faite.",
    },
    "run": {
      title: "Le monstre court",
      mission: "Que le monstre aille tout seul jusqu'à l'étoile.",
      steps: ["Place « court vers » entre le symbole du monstre et celui de l'étoile", "Regarde : le monstre court tout seul"],
      praise: "Monstre + court vers + étoile : le monstre va à l'étoile tout seul, sans que tu touches rien.",
    },
    "push": {
      title: "Livraison spatiale",
      mission: "Amène le colis jusqu'à l'étoile.",
      steps: ["Glisse « pousse » entre le symbole du personnage et celui de la caisse", "Déplace-toi avec les flèches et pousse la caisse jusqu'à l'étoile"],
      praise: "Personnage + pousse + caisse : le personnage peut pousser des caisses.",
    },
    "walls": {
      title: "Fixe les limites du mouvement",
      mission: "Que le monstre reste de l'autre côté du mur.",
      steps: ["Glisse « ne passe pas » entre le symbole du monstre et celui du mur", "Regarde ce que fait le monstre"],
      praise: "Monstre + ne passe pas + mur : le monstre ne peut pas traverser les murs.",
    },
    "eyes": {
      title: "Les yeux",
      mission: "Vois ce que dit une règle, sans jouer.",
      steps: ["Glisse les yeux dans la petite case, à côté de l'étoile"],
      praise: "Les yeux montrent ce que dit la règle : ici, l'étoile devient un cœur.",
    },
    "sun": {
      title: "Le soleil se lève",
      mission: "Fais sortir le soleil au-dessus des nuages.",
      steps: ["Glisse « téléporte » entre le symbole du soleil et celui du nuage", "Déplace le mouton jusqu'à l'herbe"],
      praise: "Quand le mouton cogne l'herbe, le soleil apparaît dans le nuage. Une collision peut faire apparaître des choses.",
    },
    "eat-all": {
      title: "Mange des fruits, et des étoiles aussi",
      mission: "Que le personnage fasse disparaître toutes les pommes et toutes les étoiles.",
      steps: ["Glisse le trou noir où il faut", "Passe maintenant sur les pommes et les étoiles"],
      praise: "Une règle pour chaque chose à manger. Avec deux règles, le personnage mange deux choses.",
    },
    "portal": {
      title: "Le portail",
      mission: "Téléporte-toi de l'autre côté du mur et atteins l'étoile.",
      steps: ["Glisse « téléporte » entre le symbole du personnage et celui de la porte", "Entre dans le portail et atteins l'étoile"],
      praise: "Le personnage cogne le portail → le personnage apparaît à la porte. Voilà comment un personnage se téléporte.",
    },
    "pull": {
      title: "Tirer des choses",
      mission: "Emmène la caisse avec toi jusqu'à l'étoile.",
      steps: ["Glisse « tire » entre le symbole du personnage et celui de la caisse", "Amène le personnage à l'étoile. La caisse le suit"],
      praise: "Personnage + tire + caisse : la caisse va derrière le personnage.",
    },
    "nobody-passes": {
      title: "Personne ne passe",
      mission: "Garde le fantôme enfermé et atteins l'étoile.",
      steps: ["Glisse le joker à côté de « ne passe pas »", "Amène le personnage à l'étoile. Le fantôme ne peut pas l'attraper"],
      praise: "Le joker vaut pour tout : aucun personnage ne traverse le mur, ni le fantôme ni toi.",
    },
    "food": {
      title: "Un repas équilibré",
      mission: "Que le personnage mange des pommes et du poisson.",
      steps: ["Glisse « est dans » entre le symbole du poisson et celui de la nourriture", "Maintenant, mange tout"],
      praise: "La pomme est dans l'idée de nourriture, le poisson aussi : une seule règle permet de manger des aliments différents. Ça, c'est une catégorie.",
    },
    "one-rule": {
      title: "Une règle pour beaucoup de choses",
      mission: "Mange trois choses différentes avec une seule règle.",
      steps: ["Glisse le symbole « nourriture » et complète la règle", "Maintenant, mange tout"],
      praise: "Trois choses différentes, une seule règle : la règle parle de la catégorie abstraite, pas de chaque chose concrète.",
    },
    "day-night": {
      title: "Du jour vient la nuit",
      mission: "Transforme le soleil en lune.",
      steps: ["Glisse « se transforme en » entre le symbole du soleil et celui de la lune", "Mets maintenant les yeux à côté du symbole du soleil, celui du haut"],
      praise: "Soleil → lune : le soleil se transforme en lune. C'est une règle qui remplace un symbole par un autre.",
    },
    "chain": {
      title: "Transformation en chaîne",
      mission: "Transforme le soleil en étoile, pas à pas.",
      steps: ["Glisse « se transforme en » entre le symbole de la lune et celui de l'étoile", "Mets maintenant les yeux à côté du symbole du soleil, en haut"],
      praise: "Soleil → lune → étoile : les substitutions s'enchaînent jusqu'au bout.",
    },
    "break-rule": {
      title: "Efface la règle en jouant",
      mission: "Casse ta propre règle pour pouvoir traverser le mur.",
      steps: ["Pousse un symbole de la règle qui t'empêche de traverser le mur", "Maintenant, traverse le mur jusqu'à l'étoile"],
      praise: "Le personnage peut modifier des règles. Le jeu change ses propres règles pendant que tu joues.",
    },
    "rule-by-playing": {
      title: "Crée la règle en jouant",
      mission: "Fais la règle en poussant des symboles et amène la caisse à l'étoile.",
      steps: ["Pousse « tire » entre les deux symboles isolés", "Amène maintenant la caisse jusqu'à l'étoile : la caisse te suit"],
      praise: "Tu as fait une règle sans prendre de tuiles en bas : en poussant des symboles sur le plateau.",
    },
    "fire": {
      title: "En plein dans le mille",
      mission: "Tire une flèche sur le fantôme.",
      steps: ["Glisse « court vers » dans la petite case, entre la flèche et le fantôme", "Appuie sur la barre d'espace"],
      praise: "La barre d'espace fait apparaître la flèche au vaisseau, et la flèche court vers le fantôme. Deux règles, un tir en plein dans le mille.",
    },
    "missile": {
      title: "Fais-le disparaître",
      mission: "Abats le fantôme avec une flèche.",
      steps: ["Glisse le trou noir dans la petite case au bout de la règle du haut", "Appuie sur la barre d'espace"],
      praise: "Quand la flèche cogne le fantôme, le fantôme tombe dans le trou noir. Il disparaît pour de bon.",
    },
    "next": {
      title: "Le nombre suivant",
      mission: "Relie les nombres.",
      steps: ["Mets les yeux à côté du 2 en haut", "Glisse maintenant le 3 dans la petite case : après 2 vient 3"],
      praise: "Il n'y a pas de nombres dans Diálogo : c'est toi qui les inventes. « Suivant de 2 → 3 » est une règle comme une autre.",
    },
    "score": {
      title: "Points",
      mission: "Fais monter les points quand tu touches une étoile.",
      steps: ["Glisse « pointe vers » dans la petite case au bout de la règle", "Mets les yeux à côté des points", "Cogne les deux étoiles et regarde les points"],
      praise: "Cogner ne met pas un nombre : ça remplace la règle « points → 0 » par « points → 1 », et ainsi de suite. Ça ajoute un à chaque fois.",
    },
    "add-zero": {
      title: "Zéro plus un nombre",
      mission: "Représente l'addition de zéro et d'un nombre.",
      steps: ["Mets les yeux à côté du 2 en haut", "Glisse maintenant l'idée de « nombre » dans la case de la fin"],
      praise: "Zéro plus un nombre, c'est ce nombre. L'addition commence par cette règle : le cas de base.",
    },
    "build-chess": {
      title: "Échecs",
      mission: "Touche le crayon et dessine une pièce noire",
      steps: ["Touche le crayon et dessine une pièce noire", "Dessine maintenant une pièce blanche", "Pose une pièce noire et une pièce blanche sur le plateau", "Fais la règle : pièce noire · flèches", "Fais la règle pour manger : noire · cogne · blanche · se transforme en · blanche · téléporte · trou noir", "Mange la pièce blanche"],
      praise: "Tu as construit un petit jeu d'échecs : tes pièces, tes règles. Le vrai ajoute des catégories : « pièce noire » pour toutes les noires.",
    },
  },
};
