// I testi del tutorial in italiano. Un verbo per frase, nominare ciò che si vede.
export const it = {
  ui: {
    "nav.play": "Tutorial",
    "nav.home": "Inizio",
    "nav.mine": "I miei",
    "nav.badges": "Medaglie",
    "nav.create": "Crea",
    "mine.title": "I miei",
    "mine.projects": "progetti",
    "mine.badges": "medaglie",
    "badges.title": "Medaglie",
    "app.title": "Introduzione a Diálogo",
    "play.title": "Introduzione a Diálogo",
    "play.subtitle": "Un tutorial per cominciare: gioca, impara le regole e poi scarica Diálogo.",
    "play.goal": "Obiettivo",
    "play.previous": "Livello precedente",
    "play.redo": "Giocalo di nuovo",
    "play.next": "Prossima sfida",
    "play.locked": "Finisci le sfide per sbloccare",
    "play.builds": "Costruisci i tuoi giochi",
    "play.free": "Creazione libera",
    "play.startOver": "Ricominciare da zero",
    "play.startOverConfirm": "Ricominciare da zero? Le tue sfide e medaglie vengono cancellate. I tuoi progetti restano.",
    "play.freeHint": "Si sblocca quando finisci di costruire i giochi",
    "language": "Lingua",
    "sound": "Suono",
    "sound.on": "Suono: sì",
    "sound.off": "Suono: no",
    "openFile": "Apri un file .dialog.ar",
    "more": "Altro",
    "open": "Apri",
    "copyAndChange": "Copia e cambia",
    "download": "Scarica .dialog.ar",
    "myVersionOf": "La mia versione di ",
    "mineSuffix": " (mio)",
    "error.open": "Non si è potuto aprire il progetto",
    "error.copy": "Non si è potuto copiare il progetto",
    "error.file": "Non si è potuto aprire il file",
    "error.openNamed": "Non si è potuto aprire: ",
    "feed.challenge": "Sfida",
    "feed.nextChallenge": "La tua prossima sfida",
    "feed.play": "Gioca",
    "feed.live": "dal vivo",
    "feed.you": "Tu",
    "feed.empty": "Crea il tuo primo progetto",
    "feed.watchOnly": "Questo progetto si guarda, non si comanda",
    "category.games": "Gioco",
    "category.didactic": "Lezione",
    "category.mine": "Mio",
    "success.title": "Ce l'hai fatta!",
    "success.next": "Avanti",
    "success.home": "Inizio",
    "success.stay": "Resta e inventa",
    "success.yours": "Adesso è tuo. Cambia quello che vuoi. Lo trovi in «I miei».",
    "menu.backToStart": "Torna all'inizio",
    "menu.forBuilding": "Per costruire",
    "menu.setStart": "Fissa questo inizio",
    "menu.reuse": "Usa pezzi di altri progetti",
    "challenge.restart": "Ricomincia",
    "tray.draw": "Disegna",
    "tray.drawing": "Disegno",
    "tray.symbol": "Pezzo",
    "joystick.space": "Spazio",
    "joystick.enter": "Invio",
    "paint.title": "Disegna",
    "paint.done": "Fatto",
    "paint.close": "Chiudi senza salvare",
    "paint.brush": "Pennello",
    "paint.eraser": "Gomma",
    "paint.bucket": "Secchiello",
    "paint.undo": "Annulla",
    "paint.size": "Spessore",
    "paint.canvas": "Tela",
    "color.black": "Nero",
    "color.orange": "Arancione",
    "color.blue": "Blu",
    "color.brown": "Marrone",
    "color.white": "Bianco",
    "color.red": "Rosso",
    "color.yellow": "Giallo",
    "color.green": "Verde",
    "color.purple": "Viola",
    "color.pink": "Rosa",
    "color.cyan": "Azzurro",
    "color.gray": "Grigio",
    "badge.first-drop": "Primo pezzo|Metti un pezzo sulla scacchiera",
    "badge.rule": "Prima regola|Costruisci una regola con i pezzi",
    "badge.first-move": "In movimento|Muovi il personaggio per la prima volta",
    "badge.artist": "Disegnatore|Disegna un pezzo nuovo",
    "badge.detective": "Detective|Usa gli occhietti per vedere cosa dice una regola",
    "badge.explorer": "Esploratore|Apri tre progetti",
    "badge.remix": "Inventore|Copia un progetto e cambialo",
    "badge.saver": "Collezionista|Salva un progetto tuo",
    "badge.world": "Mondo completo|Finisci tutte le sfide di un mondo",
    "badge.ladder": "Campione|Finisci tutte le sfide",
    "end.title": "Eccellente!",
    "end.text": "Hai completato il tutorial web. Adesso scarica l'ambiente da dialog.ar e fai il tuo primo progetto di scacchi con i tuoi disegni.",
    "end.download": "Scarica Diálogo",
    "end.watch": "Lezione 1: Scacchi (video)",
    "end.later": "Non adesso",
    "world.primeros": "Primi passi",
    "world.choques": "Scontri",
    "world.categorias": "Categorie",
    "world.sustitucion": "Sostituzione",
    "world.metaprogramacion": "Regole che cambiano",
    "world.naves": "Navi e tempo",
    "world.numeros": "Numeri",
    "world.puntos": "Punti",
    "world.builds": "Costruisci i tuoi giochi",
  },
  challenges: {
    "reach-star": {
      title: "Arriva alla stella",
      mission: "Porta il personaggio fino alla stella.",
      steps: ["Porta il personaggio fino alla stella con le frecce"],
      praise: "Il personaggio è accanto alle frecce: per questo si muove.",
    },
    "make-rule": {
      title: "Costruisci la regola",
      mission: "Fai muovere il personaggio e portalo alla stella.",
      steps: ["Trascina le frecce nel quadratino, accanto al personaggio", "Adesso si muove! Portalo fino alla stella"],
      praise: "Personaggio + frecce = si muove. Questa è una regola.",
    },
    "eat-star": {
      title: "Mangia le stelle",
      mission: "Fai togliere al personaggio tutte le stelle dalla scacchiera.",
      steps: ["Trascina il buco nero nel quadratino alla fine della regola", "Adesso sbatti contro le due stelle"],
      praise: "Quando il personaggio sbatte contro una stella, la stella cade nel buco nero: sparisce per sempre.",
    },
    "draw": {
      title: "Disegna",
      mission: "Disegna il tuo personaggio.",
      steps: ["Tocca la matita. Disegna il tuo personaggio"],
      praise: "Il tuo disegno adesso è un personaggio. Poi lo facciamo muovere.",
    },
    "bring-to-life": {
      title: "Dagli vita",
      mission: "Dai vita al tuo disegno e portalo alla stella.",
      steps: ["Trascina il tuo disegno nel quadratino, accanto alle frecce", "Il tuo disegno si muove! Portalo fino alla stella"],
      praise: "Il tuo disegno + frecce = il tuo disegno si muove. Questa regola l'hai fatta tu.",
    },
    "run": {
      title: "Il mostro corre",
      mission: "Fai arrivare il mostro alla stella da solo.",
      steps: ["Trascina «corre verso» nel quadratino, tra il mostro e la stella", "Guarda: il mostro corre da solo"],
      praise: "Mostro + corre verso + stella: il mostro va alla stella da solo, senza che tu tocchi niente.",
    },
    "push": {
      title: "Spingi la scatola",
      mission: "Porta la scatola sulla stella.",
      steps: ["Trascina «spinge» nel quadratino, tra il personaggio e la scatola", "Adesso spingi la scatola fino alla stella"],
      praise: "Personaggio + spinge + scatola: quando il personaggio sbatte contro la scatola, la scatola si muove.",
    },
    "walls": {
      title: "Il muro",
      mission: "Ferma il mostro con il muro così non ti prende.",
      steps: ["Trascina «non passa» nel quadratino, tra il mostro e il muro", "Guarda cosa fa il mostro"],
      praise: "Mostro + non passa + muro: il mostro corre, ma il muro lo ferma.",
    },
    "eyes": {
      title: "Gli occhietti",
      mission: "Vedi cosa dice una regola, senza giocare.",
      steps: ["Trascina gli occhietti nel quadratino, accanto alla stella"],
      praise: "Gli occhietti mostrano cosa dice la regola: qui la stella diventa un cuore.",
    },
    "sun": {
      title: "Esce il sole",
      mission: "Fai uscire il sole sopra le nuvole.",
      steps: ["Trascina «teletrasporta» nel quadratino, tra il sole e la nuvola", "Porta la pecora fino all'erba"],
      praise: "Quando la pecora sbatte contro l'erba, il sole appare tra le nuvole. Uno scontro può far apparire le cose.",
    },
    "eat-all": {
      title: "Mangia tutto",
      mission: "Fai togliere al personaggio tutte le mele e tutte le stelle.",
      steps: ["Trascina il buco nero nel quadratino", "Adesso mangia le mele e le stelle"],
      praise: "Una regola per ogni cosa da mangiare. Con due regole, il personaggio mangia due cose.",
    },
    "portal": {
      title: "Il portale",
      mission: "Fai attraversare il muro al personaggio fino alla stella.",
      steps: ["Trascina «teletrasporta» nel quadratino, tra il personaggio e la porta", "Entra nel portale e arriva alla stella"],
      praise: "Il personaggio sbatte contro il portale → il personaggio appare alla porta. Così si attraversa un muro.",
    },
    "pull": {
      title: "Tira la scatola",
      mission: "Porta la scatola con te fino alla stella.",
      steps: ["Trascina «tira» nel quadratino, tra il personaggio e la scatola", "Porta il personaggio alla stella. La scatola lo segue"],
      praise: "Personaggio + tira + scatola: la scatola va dietro al personaggio.",
    },
    "nobody-passes": {
      title: "Non passa nessuno",
      mission: "Lascia fuori il fantasma e arriva alla stella.",
      steps: ["Trascina il jolly nel quadratino, prima di «non passa»", "Porta il personaggio alla stella. Il fantasma non passa"],
      praise: "Il jolly vale per qualunque cosa: nessuno passa il muro, né il fantasma né tu.",
    },
    "food": {
      title: "È tutto cibo",
      mission: "Fai mangiare al personaggio mele e pesce: una dieta equilibrata.",
      steps: ["Trascina «sta dentro» nel quadratino, tra il pesce e il cibo", "Adesso mangia tutto"],
      praise: "La mela sta dentro il cibo, e anche il pesce: una sola regola li mangia tutti e due. Questa è una categoria.",
    },
    "one-rule": {
      title: "Una regola per tutto",
      mission: "Mangia tre cose diverse con una sola regola.",
      steps: ["Trascina «cibo» nei due quadratini della regola", "Adesso mangia tutto"],
      praise: "Tre cose diverse, una regola sola: la regola parla della categoria, non di ogni cosa.",
    },
    "day-night": {
      title: "Giorno e notte",
      mission: "Trasforma il sole in luna.",
      steps: ["Trascina «diventa» nel quadratino, tra il sole e la luna", "Adesso metti gli occhietti accanto al sole in alto"],
      praise: "Sole → luna: il sole diventa luna. Questa è una sostituzione.",
    },
    "chain": {
      title: "In catena",
      mission: "Trasforma il sole in stella, passo dopo passo.",
      steps: ["Trascina «diventa» nel quadratino, tra la luna e la stella", "Adesso metti gli occhietti accanto al sole in alto"],
      praise: "Sole → luna → stella: le sostituzioni si incatenano fino alla fine.",
    },
    "break-rule": {
      title: "Rompi la regola",
      mission: "Rompi la tua regola per attraversare il muro.",
      steps: ["Spingi «non passa» fuori dalla regola", "Adesso attraversa il muro fino alla stella"],
      praise: "Hai spinto un pezzo del tuo programma. Il gioco cambia le proprie regole mentre giochi.",
    },
    "rule-by-playing": {
      title: "Costruisci una regola giocando",
      mission: "Costruisci una regola spingendo i suoi pezzi e arriva alla stella.",
      steps: ["Spingi «tira» nel quadratino della regola", "Adesso porta il personaggio alla stella. La scatola lo segue"],
      praise: "Hai costruito una regola senza il vassoio: spingendo i suoi pezzi sulla scacchiera.",
    },
    "fire": {
      title: "Nel segno",
      mission: "Colpisci il fantasma con una freccia.",
      steps: ["Trascina «corre verso» nel quadratino, tra la freccia e il fantasma", "Premi la barra spaziatrice"],
      praise: "La barra fa apparire la freccia sulla nave, e la freccia corre verso il fantasma. Due regole, un colpo nel segno.",
    },
    "missile": {
      title: "Falla sparire",
      mission: "Abbatti il fantasma così sparisce.",
      steps: ["Trascina il buco nero nel quadratino alla fine della regola in alto", "Premi la barra spaziatrice"],
      praise: "Una regola in più: quando la freccia sbatte contro il fantasma, il fantasma cade nel buco nero. Sparisce per sempre.",
    },
    "next": {
      title: "Il successivo",
      mission: "Inventa il numero 3.",
      steps: ["Metti gli occhietti accanto al 2 in alto", "Adesso trascina il 3 nel quadratino: il successivo di 2 è 3"],
      praise: "In Diálogo non ci sono numeri: li inventi tu. «Successivo di 2 → 3» è una regola come tutte le altre.",
    },
    "score": {
      title: "Punti",
      mission: "Fai salire i punti quando mangi una stella.",
      steps: ["Trascina «punta a» nel quadratino alla fine della regola", "Metti gli occhietti accanto ai punti", "Sbatti contro le due stelle e guarda i punti"],
      praise: "Sbattere non mette un numero: scambia la regola «punti → 0» con «punti → il successivo». Aggiunge uno ogni volta. Senza variabili.",
    },
    "add-zero": {
      title: "Sommare zero",
      mission: "Insegna a Diálogo a sommare zero.",
      steps: ["Metti gli occhietti accanto al 2 in alto", "Adesso trascina «numero» nel quadratino alla fine della regola"],
      praise: "Zero più un numero è quel numero. La somma comincia con questa regola: il caso base.",
    },
    "build-chess": {
      title: "Scacchi",
      mission: "Tocca la matita e disegna un pezzo nero",
      steps: ["Tocca la matita e disegna un pezzo nero", "Adesso disegna un pezzo bianco", "Metti un pezzo nero e un pezzo bianco sulla scacchiera", "Costruisci la regola: pezzo nero · frecce", "Costruisci la regola per mangiare: nero · sbatte · bianco · diventa · bianco · teletrasporta · buco nero", "Mangia il pezzo bianco"],
      praise: "Hai costruito un piccolo gioco di scacchi: i tuoi pezzi, le tue regole. Quello vero aggiunge le categorie: «pezzo nero» per tutti i neri.",
    },
  },
};
