// I testi del tutorial in italiano. Un verbo per frase, nominare ciò che si vede.
export const it = {
  ui: {
    "nav.play": "Percorso",
    "nav.home": "Inizio",
    "nav.mine": "I miei",
    "nav.badges": "Medaglie",
    "nav.create": "Crea",
    "mine.title": "I miei",
    "mine.projects": "progetti",
    "mine.badges": "medaglie",
    "badges.title": "Medaglie",
    "app.title": "Introduzione a Diálogo",
    "play.title": "Un'introduzione giocando",
    "play.subtitle": "Un'introduzione divertente: gioca, conosci i simboli di base e poi scarica Diálogo sul tuo computer per fare i progetti.",
    "play.goal": "Obiettivo",
    "play.previous": "Livello precedente",
    "play.redo": "Giocalo di nuovo",
    "play.next": "Prossima sfida",
    "play.locked": "Finisci le sfide per sbloccare",
    "play.builds": "Costruisci i tuoi giochi",
    "play.free": "Creazione libera",
    "play.startOver": "Ricominciare da zero",
    "play.startOverConfirm": "Ricominciare da zero? Le tue sfide e medaglie vengono cancellate.",
    "play.freeHint": "Si sblocca quando finisci di costruire i giochi",
    "language": "Lingua",
    "sound": "Suono",
    "sound.on": "Suono: sì",
    "sound.off": "Suono: no",
    "openFile": "Apri un file .dialog.ar",
    "more": "Altro",
    "open": "Apri",
    "copyAndChange": "Copia e cambia",
    "download": "Scarica .dialog.ar",
    "myVersionOf": "La mia versione di",
    "mineSuffix": "(mio)",
    "error.open": "Non si è potuto aprire il progetto",
    "error.copy": "Non si è potuto copiare il progetto",
    "error.file": "Non si è potuto aprire il file",
    "error.openNamed": "Non si è potuto aprire:",
    "feed.challenge": "Sfida",
    "feed.nextChallenge": "La tua prossima sfida",
    "feed.play": "Gioca",
    "feed.live": "dal vivo",
    "feed.you": "Tu",
    "feed.empty": "Crea il tuo primo progetto",
    "feed.watchOnly": "Questo progetto si guarda, non si comanda",
    "category.games": "Gioco",
    "category.didactic": "Lezione",
    "category.mine": "Mio",
    "success.title": "Ce l'hai fatta!",
    "success.next": "Avanti",
    "success.home": "Inizio",
    "success.stay": "Resta e inventa",
    "success.yours": "Adesso è tuo. Cambia quello che vuoi. Lo trovi in «I miei».",
    "menu.backToStart": "Torna all'inizio",
    "menu.forBuilding": "Per costruire",
    "menu.setStart": "Fissa questo inizio",
    "menu.reuse": "Usa pezzi di altri progetti",
    "challenge.restart": "Ricomincia",
    "tray.draw": "Disegna",
    "tray.drawing": "Disegno",
    "tray.symbol": "Pezzo",
    "joystick.space": "Spazio",
    "joystick.enter": "Invio",
    "paint.title": "Disegna",
    "paint.done": "Fatto",
    "paint.close": "Chiudi senza salvare",
    "paint.brush": "Pennello",
    "paint.eraser": "Gomma",
    "paint.bucket": "Secchiello",
    "paint.undo": "Annulla",
    "paint.size": "Spessore",
    "paint.canvas": "Tela",
    "color.black": "Nero",
    "color.orange": "Arancione",
    "color.blue": "Blu",
    "color.brown": "Marrone",
    "color.white": "Bianco",
    "color.red": "Rosso",
    "color.yellow": "Giallo",
    "color.green": "Verde",
    "color.purple": "Viola",
    "color.pink": "Rosa",
    "color.cyan": "Azzurro",
    "color.gray": "Grigio",
    "badge.first-drop": "Primo pezzo|Metti un pezzo sulla scacchiera",
    "badge.rule": "Prima regola|Costruisci una regola con i pezzi",
    "badge.first-move": "In movimento|Muovi il personaggio per la prima volta",
    "badge.artist": "Disegnatore|Disegna un pezzo nuovo",
    "badge.detective": "Detective|Usa gli occhietti per vedere cosa dice una regola",
    "badge.explorer": "Esploratore|Apri tre progetti",
    "badge.remix": "Inventore|Copia un progetto e cambialo",
    "badge.saver": "Collezionista|Salva un progetto tuo",
    "badge.world": "Mondo completo|Finisci tutte le sfide di un mondo",
    "badge.ladder": "Campione|Finisci tutte le sfide",
    "end.title": "Congratulazioni!",
    "end.text": "Hai capito le basi di Diálogo. Puoi continuare con i progetti seguendo i videotutorial. Il prossimo passo è scaricare Diálogo e poi fare il primo progetto di scacchi.",
    "end.note": "Diálogo si installa su un computer: dal telefono non si può continuare.",
    "end.download": "Scarica Diálogo sul computer",
    "end.watch": "Lezione 1: Scacchi (video)",
    "end.later": "Non adesso",
    "world.primeros": "Primi passi",
    "world.choques": "Scontri",
    "world.categorias": "Categorie",
    "world.sustitucion": "Sostituzione",
    "world.metaprogramacion": "Regole che cambiano",
    "world.naves": "Navi e tempo",
    "world.numeros": "Numeri",
    "world.puntos": "Punti",
    "world.builds": "Costruisci i tuoi giochi",
  },
  challenges: {
    "reach-star": {
      title: "Viaggio verso le stelle",
      mission: "Porta il personaggio fino alla stella.",
      steps: ["Muovi il personaggio con le frecce"],
      praise: "Il simbolo del personaggio è accanto a quello delle frecce: per questo si muove.",
    },
    "make-rule": {
      title: "Costruisci la tua prima regola",
      mission: "Porta il personaggio fino alla stella.",
      steps: ["Trascina le frecce accanto al simbolo del personaggio", "Adesso si può muovere! Portalo alla stella"],
      praise: "Personaggio + frecce = si muove. Questa è una regola.",
    },
    "eat-star": {
      title: "Mangia le stelle",
      mission: "Che il personaggio cancelli dalla scacchiera tutte le stelle.",
      steps: ["Trascina il buco nero e completa la regola", "Adesso passa sopra le due stelle"],
      praise: "Quando il personaggio sbatte contro una stella, la stella cade nel buco nero: sparisce per sempre.",
    },
    "draw": {
      title: "Disegna",
      mission: "Disegna il tuo personaggio.",
      steps: ["Tocca la matita. Disegna."],
      praise: "Il tuo disegno adesso è un personaggio. Poi lo facciamo muovere.",
    },
    "bring-to-life": {
      title: "Dai vita al tuo personaggio",
      mission: "Porta il tuo personaggio fino alla stella.",
      steps: ["Trascina il simbolo del tuo personaggio accanto a quello delle frecce", "Il tuo personaggio si può muovere! Portalo fino alla stella"],
      praise: "Il tuo disegno + frecce = il tuo disegno si muove. Questa regola l'hai fatta tu.",
    },
    "run": {
      title: "Il mostro corre",
      mission: "Che il mostro vada da solo fino alla stella.",
      steps: ["Metti «corre verso» tra il simbolo del mostro e quello della stella", "Guarda: il mostro corre da solo"],
      praise: "Mostro + corre verso + stella: il mostro va alla stella da solo, senza che tu tocchi niente.",
    },
    "push": {
      title: "Posta spaziale",
      mission: "Porta il pacco fino alla stella.",
      steps: ["Trascina «spinge» tra il simbolo del personaggio e quello della scatola", "Muoviti con le frecce e spingi la scatola fino alla stella"],
      praise: "Personaggio + spinge + scatola: il personaggio può spingere le scatole.",
    },
    "walls": {
      title: "Definisci i limiti del movimento",
      mission: "Che il mostro resti dall'altra parte del muro.",
      steps: ["Trascina «non passa» tra il simbolo del mostro e quello del muro", "Guarda cosa fa il mostro"],
      praise: "Mostro + non passa + muro: il mostro non può attraversare i muri.",
    },
    "eyes": {
      title: "Gli occhietti",
      mission: "Vedi cosa dice una regola, senza giocare.",
      steps: ["Trascina gli occhietti nel quadratino, accanto alla stella"],
      praise: "Gli occhietti mostrano cosa dice la regola: qui la stella diventa un cuore.",
    },
    "sun": {
      title: "Esce il sole",
      mission: "Fai uscire il sole sopra le nuvole.",
      steps: ["Trascina «teletrasporta» tra il simbolo del sole e quello della nuvola", "Muovi la pecora fino all'erba"],
      praise: "Quando la pecora sbatte contro l'erba, il sole appare nella nuvola. Una collisione può far apparire le cose.",
    },
    "eat-all": {
      title: "Mangia tanta frutta, e anche stelle",
      mission: "Che il personaggio faccia sparire tutte le mele e tutte le stelle.",
      steps: ["Trascina il buco nero dove va", "Adesso passa sopra le mele e le stelle"],
      praise: "Una regola per ogni cosa da mangiare. Con due regole, il personaggio mangia due cose.",
    },
    "portal": {
      title: "Il portale",
      mission: "Teletrasportati dall'altra parte del muro e arriva alla stella.",
      steps: ["Trascina «teletrasporta» tra il simbolo del personaggio e quello della porta", "Entra nel portale e raggiungi la stella"],
      praise: "Il personaggio sbatte contro il portale → il personaggio appare alla porta. Così un personaggio si teletrasporta.",
    },
    "pull": {
      title: "Tirare le cose",
      mission: "Porta la scatola con te fino alla stella.",
      steps: ["Trascina «tira» tra il simbolo del personaggio e quello della scatola", "Porta il personaggio alla stella. La scatola lo segue"],
      praise: "Personaggio + tira + scatola: la scatola va dietro al personaggio.",
    },
    "nobody-passes": {
      title: "Non passa nessuno",
      mission: "Lascia il fantasma intrappolato e arriva alla stella.",
      steps: ["Trascina il jolly accanto a «non passa»", "Porta il personaggio alla stella. Il fantasma non riesce a raggiungerlo"],
      praise: "Il jolly vale per qualunque cosa: nessun personaggio attraversa il muro, né il fantasma né tu.",
    },
    "food": {
      title: "Una dieta equilibrata",
      mission: "Che il personaggio mangi mele e pesce.",
      steps: ["Trascina «sta dentro» tra il simbolo del pesce e quello del cibo", "Adesso mangia tutto"],
      praise: "La mela sta dentro l'idea di cibo, e anche il pesce: una sola regola permette di mangiare cibi diversi. Questa è una categoria.",
    },
    "one-rule": {
      title: "Una regola per tanti oggetti",
      mission: "Mangia tre cose diverse con una sola regola.",
      steps: ["Trascina il simbolo «cibo» e completa la regola", "Adesso mangia tutto"],
      praise: "Tre cose diverse, una sola regola: la regola parla della categoria astratta, non di ogni cosa concreta.",
    },
    "day-night": {
      title: "Dal giorno viene la notte",
      mission: "Trasforma il sole in luna.",
      steps: ["Trascina «diventa» tra il simbolo del sole e quello della luna", "Adesso metti gli occhietti accanto al simbolo del sole, quello più in alto"],
      praise: "Sole → luna: il sole diventa luna. È una regola che sostituisce un simbolo con un altro.",
    },
    "chain": {
      title: "Trasformazione in catena",
      mission: "Trasforma il sole in stella, passo dopo passo.",
      steps: ["Trascina «diventa» tra il simbolo della luna e quello della stella", "Adesso metti gli occhietti accanto al simbolo del sole in alto"],
      praise: "Sole → luna → stella: le sostituzioni si incatenano fino alla fine.",
    },
    "break-rule": {
      title: "Cancella la regola giocando",
      mission: "Rompi la tua stessa regola per poter attraversare il muro.",
      steps: ["Spingi un simbolo della regola che ti impedisce di attraversare il muro", "Adesso attraversa il muro fino alla stella"],
      praise: "Il personaggio può modificare le regole. Il gioco cambia le proprie regole mentre giochi.",
    },
    "rule-by-playing": {
      title: "Crea la regola giocando",
      mission: "Costruisci una regola spingendo simboli e arriva alla stella.",
      steps: ["Spingi «tira» tra i due simboli sciolti", "Adesso porta il personaggio fino alla scatola e passa sopra la stella. La scatola lo segue"],
      praise: "Hai costruito una regola senza prendere pezzi dalla barra: spingendo simboli sulla scacchiera.",
    },
    "fire": {
      title: "Nel segno",
      mission: "Colpisci il fantasma con una freccia.",
      steps: ["Trascina «corre verso» nel quadratino, tra la freccia e il fantasma", "Premi la barra spaziatrice"],
      praise: "La barra fa apparire la freccia sulla nave, e la freccia corre verso il fantasma. Due regole, un colpo nel segno.",
    },
    "missile": {
      title: "Falla sparire",
      mission: "Abbatti il fantasma con una freccia.",
      steps: ["Trascina il buco nero nel quadratino alla fine della regola in alto", "Premi la barra spaziatrice"],
      praise: "Quando la freccia sbatte contro il fantasma, il fantasma cade nel buco nero. Sparisce per sempre.",
    },
    "next": {
      title: "Il numero successivo",
      mission: "Collega i numeri.",
      steps: ["Metti gli occhietti accanto al 2 in alto", "Adesso trascina il 3 nel quadratino: dopo il 2 viene il 3"],
      praise: "In Diálogo non ci sono numeri: li inventi tu. «Successivo di 2 → 3» è una regola come tutte le altre.",
    },
    "score": {
      title: "Punti",
      mission: "Fai salire i punti quando tocchi una stella.",
      steps: ["Trascina «punta a» nel quadratino alla fine della regola", "Metti gli occhietti accanto ai punti", "Sbatti contro le due stelle e guarda i punti"],
      praise: "Sbattere non mette un numero: scambia la regola «punti → 0» con «punti → 1», e così via. Aggiunge uno ogni volta.",
    },
    "add-zero": {
      title: "Zero più un numero",
      mission: "Rappresenta la somma di zero e un numero.",
      steps: ["Metti gli occhietti accanto al 2 in alto", "Adesso trascina l'idea di «numero» nel quadratino finale"],
      praise: "Zero più un numero è quel numero. La somma comincia con questa regola: il caso base.",
    },
    "build-chess": {
      title: "Scacchi",
      mission: "Tocca la matita e disegna un pezzo nero",
      steps: ["Tocca la matita e disegna un pezzo nero", "Adesso disegna un pezzo bianco", "Metti un pezzo nero e un pezzo bianco sulla scacchiera", "Costruisci la regola: pezzo nero · frecce", "Costruisci la regola per mangiare: nero · sbatte · bianco · diventa · bianco · teletrasporta · buco nero", "Mangia il pezzo bianco"],
      praise: "Hai costruito un piccolo gioco di scacchi: i tuoi pezzi, le tue regole. Quello vero aggiunge le categorie: «pezzo nero» per tutti i neri.",
    },
  },
};
