// Os textos do tutorial em português. Um verbo por frase, nomear o que se vê.
export const pt = {
  ui: {
    "nav.play": "Tutorial",
    "nav.home": "Início",
    "nav.mine": "Meus",
    "nav.badges": "Medalhas",
    "nav.create": "Criar",
    "mine.title": "Meus",
    "mine.projects": "projetos",
    "mine.badges": "medalhas",
    "badges.title": "Medalhas",
    "app.title": "Introdução ao Diálogo",
    "play.title": "Introdução ao Diálogo",
    "play.subtitle": "Um tutorial para começar: jogue, aprenda as regras e depois baixe o Diálogo.",
    "play.goal": "Objetivo",
    "play.previous": "Nível anterior",
    "play.redo": "Jogar de novo",
    "play.next": "Próximo desafio",
    "play.locked": "Termine os desafios para desbloquear",
    "play.builds": "Monte seus próprios jogos",
    "play.free": "Criação livre",
    "play.startOver": "Começar do zero",
    "play.startOverConfirm": "Começar do zero? Seus desafios e medalhas serão apagados. Seus projetos ficam.",
    "play.freeHint": "Libera quando você terminar de montar os jogos",
    "language": "Idioma",
    "sound": "Som",
    "sound.on": "Som: sim",
    "sound.off": "Som: não",
    "openFile": "Abrir um arquivo .dialog.ar",
    "more": "Mais",
    "open": "Abrir",
    "copyAndChange": "Copiar e mudar",
    "download": "Baixar .dialog.ar",
    "myVersionOf": "Minha versão de ",
    "mineSuffix": " (meu)",
    "error.open": "Não deu para abrir o projeto",
    "error.copy": "Não deu para copiar o projeto",
    "error.file": "Não deu para abrir o arquivo",
    "error.openNamed": "Não deu para abrir: ",
    "feed.challenge": "Desafio",
    "feed.nextChallenge": "Seu próximo desafio",
    "feed.play": "Jogar",
    "feed.live": "ao vivo",
    "feed.you": "Você",
    "feed.empty": "Crie seu primeiro projeto",
    "feed.watchOnly": "Este projeto é de olhar, não de controlar",
    "category.games": "Jogo",
    "category.didactic": "Aula",
    "category.mine": "Meu",
    "success.title": "Você conseguiu!",
    "success.next": "Próximo",
    "success.home": "Início",
    "success.stay": "Ficar e inventar",
    "success.yours": "Agora é seu. Mude o que quiser. Você vai encontrar em “Meus”.",
    "menu.backToStart": "Voltar ao início",
    "menu.forBuilding": "Para montar",
    "menu.setStart": "Fixar este início",
    "menu.reuse": "Usar peças de outros projetos",
    "challenge.restart": "Começar de novo",
    "tray.draw": "Desenhar",
    "tray.drawing": "Desenho",
    "tray.symbol": "Peça",
    "joystick.space": "Espaço",
    "joystick.enter": "Enter",
    "paint.title": "Desenhar",
    "paint.done": "Pronto",
    "paint.close": "Fechar sem salvar",
    "paint.brush": "Pincel",
    "paint.eraser": "Borracha",
    "paint.bucket": "Balde",
    "paint.undo": "Desfazer",
    "paint.size": "Espessura",
    "paint.canvas": "Tela",
    "color.black": "Preto",
    "color.orange": "Laranja",
    "color.blue": "Azul",
    "color.brown": "Marrom",
    "color.white": "Branco",
    "color.red": "Vermelho",
    "color.yellow": "Amarelo",
    "color.green": "Verde",
    "color.purple": "Roxo",
    "color.pink": "Rosa",
    "color.cyan": "Azul-claro",
    "color.gray": "Cinza",
    "badge.first-drop": "Primeira peça|Ponha uma peça no tabuleiro",
    "badge.rule": "Primeira regra|Monte uma regra com peças",
    "badge.first-move": "Em movimento|Mova o personagem pela primeira vez",
    "badge.artist": "Desenhista|Desenhe uma peça nova",
    "badge.detective": "Detetive|Use os olhinhos para ver o que uma regra diz",
    "badge.explorer": "Explorador|Abra três projetos",
    "badge.remix": "Inventor|Copie um projeto e mude",
    "badge.saver": "Colecionador|Salve um projeto seu",
    "badge.world": "Mundo completo|Termine todos os desafios de um mundo",
    "badge.ladder": "Campeão|Termine todos os desafios",
    "end.title": "Parabéns!",
    "end.text": "Agora você entende as bases da linguagem. Continue com os projetos, seguindo os videotutoriais: o próximo passo é baixar o Diálogo.",
    "end.download": "Baixar o Diálogo",
    "end.watch": "Aula 1: Xadrez (vídeo)",
    "end.later": "Agora não",
    "world.primeros": "Primeiros passos",
    "world.choques": "Choques",
    "world.categorias": "Categorias",
    "world.sustitucion": "Substituição",
    "world.metaprogramacion": "Regras que mudam",
    "world.naves": "Naves e tempo",
    "world.numeros": "Números",
    "world.puntos": "Pontos",
    "world.builds": "Monte seus próprios jogos",
  },
  challenges: {
    "reach-star": {
      title: "Chegue à estrela",
      mission: "Leve o personagem até a estrela.",
      steps: ["Leve o personagem até a estrela com as setas"],
      praise: "O personagem está ao lado das setas: por isso ele se move.",
    },
    "make-rule": {
      title: "Monte a regra",
      mission: "Faça o personagem se mover e chegar à estrela.",
      steps: ["Arraste as setas até o quadradinho, ao lado do personagem", "Agora ele se move! Leve-o até a estrela"],
      praise: "Personagem + setas = ele se move. Isso é uma regra.",
    },
    "eat-star": {
      title: "Coma as estrelas",
      mission: "Faça o personagem tirar todas as estrelas do tabuleiro.",
      steps: ["Arraste o buraco negro até o quadradinho no fim da regra", "Agora bata nas duas estrelas"],
      praise: "Quando o personagem bate numa estrela, a estrela cai no buraco negro: some para sempre.",
    },
    "draw": {
      title: "Desenhe",
      mission: "Desenhe o seu próprio personagem.",
      steps: ["Toque no lápis. Desenhe o seu personagem"],
      praise: "Seu desenho já é um personagem. Agora vamos fazer ele se mover.",
    },
    "bring-to-life": {
      title: "Dê vida a ele",
      mission: "Dê vida ao seu desenho e leve-o até a estrela.",
      steps: ["Arraste o seu desenho até o quadradinho, ao lado das setas", "Seu desenho se move! Leve-o até a estrela"],
      praise: "Seu desenho + setas = seu desenho se move. Essa regra foi você que montou.",
    },
    "run": {
      title: "O monstro corre",
      mission: "Faça o monstro chegar sozinho à estrela.",
      steps: ["Arraste “corre até” ao quadradinho, entre o monstro e a estrela", "Olhe: o monstro corre sozinho"],
      praise: "Monstro + corre até + estrela: o monstro vai sozinho até a estrela, sem você tocar em nada.",
    },
    "push": {
      title: "Empurre a caixa",
      mission: "Leve a caixa até a estrela.",
      steps: ["Arraste “empurra” ao quadradinho, entre o personagem e a caixa", "Agora empurre a caixa até a estrela"],
      praise: "Personagem + empurra + caixa: quando o personagem bate na caixa, a caixa se move.",
    },
    "walls": {
      title: "A parede",
      mission: "Pare o monstro com a parede para ele não te alcançar.",
      steps: ["Arraste “não passa” ao quadradinho, entre o monstro e a parede", "Veja o que o monstro faz"],
      praise: "Monstro + não passa + parede: o monstro corre, mas a parede o segura.",
    },
    "eyes": {
      title: "Os olhinhos",
      mission: "Veja o que uma regra diz, sem jogar.",
      steps: ["Arraste os olhinhos até o quadradinho, ao lado da estrela"],
      praise: "Os olhinhos mostram o que a regra diz: aqui, a estrela vira um coração.",
    },
    "sun": {
      title: "O sol aparece",
      mission: "Faça o sol aparecer sobre as nuvens.",
      steps: ["Arraste “teletransporta” ao quadradinho, entre o sol e a nuvem", "Leve a ovelha até o capim"],
      praise: "Quando a ovelha bate no capim, o sol aparece nas nuvens. Um choque pode fazer coisas aparecerem.",
    },
    "eat-all": {
      title: "Coma tudo",
      mission: "Faça o personagem tirar todas as maçãs e todas as estrelas.",
      steps: ["Arraste o buraco negro até o quadradinho", "Agora coma as maçãs e as estrelas"],
      praise: "Uma regra para cada coisa que se come. Com duas regras, o personagem come duas coisas.",
    },
    "portal": {
      title: "O portal",
      mission: "Atravesse a parede e chegue à estrela.",
      steps: ["Arraste “teletransporta” ao quadradinho, entre o personagem e a porta", "Entre no portal e chegue à estrela"],
      praise: "Personagem bate no portal → o personagem aparece na porta. É assim que se atravessa uma parede.",
    },
    "pull": {
      title: "Puxe a caixa",
      mission: "Leve a caixa junto com você até a estrela.",
      steps: ["Arraste “puxa” ao quadradinho, entre o personagem e a caixa", "Leve o personagem até a estrela. A caixa vai atrás"],
      praise: "Personagem + puxa + caixa: a caixa vai atrás do personagem.",
    },
    "nobody-passes": {
      title: "Ninguém passa",
      mission: "Deixe o fantasma de fora e chegue à estrela.",
      steps: ["Arraste o coringa até o quadradinho, antes de “não passa”", "Leve o personagem até a estrela. O fantasma não passa"],
      praise: "O coringa vale para qualquer coisa: ninguém passa a parede, nem o fantasma nem você.",
    },
    "food": {
      title: "Tudo é comida",
      mission: "Faça o personagem comer maçãs e peixe: uma dieta equilibrada.",
      steps: ["Arraste “está dentro de” ao quadradinho, entre o peixe e a comida", "Agora coma tudo"],
      praise: "A maçã está dentro de comida, o peixe também: uma regra só come os dois. Isso é uma categoria.",
    },
    "one-rule": {
      title: "Uma regra para tudo",
      mission: "Coma três coisas diferentes com uma regra só.",
      steps: ["Arraste “comida” aos dois quadradinhos da regra", "Agora coma tudo"],
      praise: "Três coisas diferentes, uma regra: a regra fala da categoria, não de cada coisa.",
    },
    "day-night": {
      title: "Dia e noite",
      mission: "Transforme o sol em lua.",
      steps: ["Arraste “vira” ao quadradinho, entre o sol e a lua", "Agora ponha os olhinhos ao lado do sol de cima"],
      praise: "Sol → lua: o sol vira lua. Isso é uma substituição.",
    },
    "chain": {
      title: "Em cadeia",
      mission: "Transforme o sol em estrela, passo a passo.",
      steps: ["Arraste “vira” ao quadradinho, entre a lua e a estrela", "Agora ponha os olhinhos ao lado do sol de cima"],
      praise: "Sol → lua → estrela: as substituições se encadeiam até o fim.",
    },
    "break-rule": {
      title: "Quebre a regra",
      mission: "Quebre a sua própria regra para atravessar a parede.",
      steps: ["Empurre “não passa” para fora da regra", "Agora atravesse a parede até a estrela"],
      praise: "Você empurrou um pedaço do seu programa. O jogo muda as próprias regras enquanto você joga.",
    },
    "rule-by-playing": {
      title: "Monte uma regra jogando",
      mission: "Monte uma regra empurrando as peças dela e chegue à estrela.",
      steps: ["Empurre “puxa” até o quadradinho da regra", "Agora leve o personagem até a estrela. A caixa vai atrás"],
      praise: "Você montou uma regra sem a bandeja: empurrando as peças pelo tabuleiro.",
    },
    "fire": {
      title: "Na mosca",
      mission: "Acerte uma flecha no fantasma.",
      steps: ["Arraste “corre até” ao quadradinho, entre a flecha e o fantasma", "Toque na barra de espaço"],
      praise: "A barra de espaço faz a flecha aparecer na nave, e a flecha corre até o fantasma. Duas regras, uma flechada.",
    },
    "missile": {
      title: "Faça sumir",
      mission: "Derrube o fantasma para ele sumir.",
      steps: ["Arraste o buraco negro até o quadradinho no fim da regra de cima", "Toque na barra de espaço"],
      praise: "Mais uma regra: quando a flecha bate no fantasma, o fantasma cai no buraco negro. Some para sempre.",
    },
    "next": {
      title: "O seguinte",
      mission: "Invente o número 3.",
      steps: ["Ponha os olhinhos ao lado do 2 de cima", "Agora arraste o 3 até o quadradinho: o seguinte de 2 é 3"],
      praise: "No Diálogo não há números: você os inventa. “Seguinte de 2 → 3” é uma regra como qualquer outra.",
    },
    "score": {
      title: "Pontos",
      mission: "Faça os pontos subirem quando você come uma estrela.",
      steps: ["Arraste “aponta para” ao quadradinho no fim da regra", "Ponha os olhinhos ao lado dos pontos", "Bata nas duas estrelas e olhe os pontos"],
      praise: "Bater não coloca um número: troca a regra “pontos → 0” por “pontos → o seguinte”. Soma um cada vez. Sem variáveis.",
    },
    "add-zero": {
      title: "Somar zero",
      mission: "Ensine o Diálogo a somar zero.",
      steps: ["Ponha os olhinhos ao lado do 2 de cima", "Agora arraste “número” até o quadradinho no fim da regra"],
      praise: "Zero mais um número é esse número. A soma começa com essa regra: o caso base.",
    },
    "build-chess": {
      title: "Xadrez",
      mission: "Toque no lápis e desenhe uma peça preta",
      steps: ["Toque no lápis e desenhe uma peça preta", "Agora desenhe uma peça branca", "Ponha uma peça preta e uma branca no tabuleiro", "Monte a regra: peça preta · setas", "Monte a regra de comer: preta · bate · branca · vira · branca · teletransporta · buraco negro", "Coma a peça branca"],
      praise: "Você montou um xadrez pequeno: suas peças, suas regras. O de verdade acrescenta categorias: “peça preta” para todas as pretas.",
    },
  },
};
