// Os textos do tutorial em português. Um verbo por frase, nomear o que se vê.
export const pt = {
  ui: {
    "nav.play": "Sequência",
    "nav.home": "Início",
    "nav.mine": "Meus",
    "nav.badges": "Medalhas",
    "nav.create": "Criar",
    "mine.title": "Meus",
    "mine.projects": "projetos",
    "mine.badges": "medalhas",
    "badges.title": "Medalhas",
    "app.title": "Introdução ao Diálogo",
    "play.title": "Uma introdução brincando",
    "play.subtitle": "Uma introdução divertida: jogue, conheça os símbolos básicos e depois baixe o Diálogo no seu computador para fazer os projetos.",
    "play.goal": "Objetivo",
    "play.previous": "Nível anterior",
    "play.redo": "Jogar de novo",
    "play.next": "Próximo desafio",
    "play.locked": "Termine os desafios para desbloquear",
    "play.builds": "Monte seus próprios jogos",
    "play.free": "Criação livre",
    "play.startOver": "Começar do zero",
    "play.startOverConfirm": "Começar do zero? Seus desafios e medalhas serão apagados.",
    "play.freeHint": "Libera quando você terminar de montar os jogos",
    "language": "Idioma",
    "sound": "Som",
    "sound.on": "Som: sim",
    "sound.off": "Som: não",
    "openFile": "Abrir um arquivo .dialog.ar",
    "more": "Mais",
    "open": "Abrir",
    "copyAndChange": "Copiar e mudar",
    "download": "Baixar .dialog.ar",
    "myVersionOf": "Minha versão de",
    "mineSuffix": "(meu)",
    "error.open": "Não deu para abrir o projeto",
    "error.copy": "Não deu para copiar o projeto",
    "error.file": "Não deu para abrir o arquivo",
    "error.openNamed": "Não deu para abrir:",
    "feed.challenge": "Desafio",
    "feed.nextChallenge": "Seu próximo desafio",
    "feed.play": "Jogar",
    "feed.live": "ao vivo",
    "feed.you": "Você",
    "feed.empty": "Crie seu primeiro projeto",
    "feed.watchOnly": "Este projeto é de olhar, não de controlar",
    "category.games": "Jogo",
    "category.didactic": "Aula",
    "category.mine": "Meu",
    "success.title": "Você conseguiu!",
    "success.next": "Próximo",
    "success.home": "Início",
    "success.stay": "Ficar e inventar",
    "success.yours": "Agora é seu. Mude o que quiser. Você vai encontrar em “Meus”.",
    "menu.backToStart": "Voltar ao início",
    "menu.forBuilding": "Para montar",
    "menu.setStart": "Fixar este início",
    "menu.reuse": "Usar peças de outros projetos",
    "challenge.restart": "Começar de novo",
    "tray.draw": "Desenhar",
    "tray.drawing": "Desenho",
    "tray.symbol": "Peça",
    "joystick.space": "Espaço",
    "joystick.enter": "Enter",
    "paint.title": "Desenhar",
    "paint.done": "Pronto",
    "paint.close": "Fechar sem salvar",
    "paint.brush": "Pincel",
    "paint.eraser": "Borracha",
    "paint.bucket": "Balde",
    "paint.undo": "Desfazer",
    "paint.size": "Espessura",
    "paint.canvas": "Tela",
    "color.black": "Preto",
    "color.orange": "Laranja",
    "color.blue": "Azul",
    "color.brown": "Marrom",
    "color.white": "Branco",
    "color.red": "Vermelho",
    "color.yellow": "Amarelo",
    "color.green": "Verde",
    "color.purple": "Roxo",
    "color.pink": "Rosa",
    "color.cyan": "Azul-claro",
    "color.gray": "Cinza",
    "badge.first-drop": "Primeira peça|Ponha uma peça no tabuleiro",
    "badge.rule": "Primeira regra|Monte uma regra com peças",
    "badge.first-move": "Em movimento|Mova o personagem pela primeira vez",
    "badge.artist": "Desenhista|Desenhe uma peça nova",
    "badge.detective": "Detetive|Use os olhinhos para ver o que uma regra diz",
    "badge.explorer": "Explorador|Abra três projetos",
    "badge.remix": "Inventor|Copie um projeto e mude",
    "badge.saver": "Colecionador|Salve um projeto seu",
    "badge.world": "Mundo completo|Termine todos os desafios de um mundo",
    "badge.ladder": "Campeão|Termine todos os desafios",
    "end.title": "Parabéns!",
    "end.text": "Você já entendeu o básico do Diálogo. Dá para seguir com os projetos pelos videotutoriais. O próximo passo é baixar o Diálogo e depois fazer o primeiro projeto de xadrez.",
    "end.note": "O Diálogo se instala num computador: pelo celular não dá para continuar.",
    "end.download": "Passo 2: Baixar o Diálogo no computador",
    "end.watch": "Aula 1: Xadrez (vídeo)",
    "end.later": "Agora não",
    "world.primeros": "Primeiros passos",
    "world.choques": "Choques",
    "world.categorias": "Categorias",
    "world.sustitucion": "Substituição",
    "world.metaprogramacion": "Regras que mudam",
    "world.naves": "Naves e tempo",
    "world.numeros": "Números",
    "world.puntos": "Pontos",
    "world.builds": "Monte seus próprios jogos",
  },
  challenges: {
    "reach-star": {
      title: "Viagem às estrelas",
      mission: "Leve o personagem até a estrela.",
      steps: ["Mova o personagem com as setas"],
      praise: "O símbolo do personagem está ao lado do das setas: por isso ele se move.",
    },
    "make-rule": {
      title: "Monte sua primeira regra",
      mission: "Leve o personagem até a estrela.",
      steps: ["Arraste as setas para o lado do símbolo do personagem", "Ele já pode se mover! Leve-o até a estrela"],
      praise: "Personagem + setas = ele se move. Isso é uma regra.",
    },
    "eat-star": {
      title: "Coma as estrelas",
      mission: "Que o personagem apague do tabuleiro todas as estrelas.",
      steps: ["Arraste o buraco negro e complete a regra", "Agora passe por cima das duas estrelas"],
      praise: "Quando o personagem bate numa estrela, a estrela cai no buraco negro: some para sempre.",
    },
    "draw": {
      title: "Desenhe",
      mission: "Desenhe o seu próprio personagem.",
      steps: ["Toque no lápis. Desenhe."],
      praise: "Seu desenho já é um personagem. Agora vamos fazer ele se mover.",
    },
    "bring-to-life": {
      title: "Dê vida ao seu personagem",
      mission: "Leve o seu personagem até a estrela.",
      steps: ["Arraste o símbolo do seu personagem para o lado do das setas", "Seu personagem já pode se mover! Leve-o até a estrela"],
      praise: "Seu desenho + setas = seu desenho se move. Essa regra foi você que montou.",
    },
    "run": {
      title: "O monstro corre",
      mission: "Que o monstro vá sozinho até a estrela.",
      steps: ["Coloque «corre até» entre o símbolo do monstro e o da estrela", "Olhe: o monstro corre sozinho"],
      praise: "Monstro + corre até + estrela: o monstro vai sozinho até a estrela, sem você tocar em nada.",
    },
    "push": {
      title: "Correio espacial",
      mission: "Leve o pacote até a estrela.",
      steps: ["Arraste «empurra» entre o símbolo do personagem e o da caixa", "Mova-se com as setas e empurre a caixa até a estrela"],
      praise: "Personagem + empurra + caixa: o personagem pode empurrar caixas.",
    },
    "walls": {
      title: "Defina os limites do movimento",
      mission: "Que o monstro fique do outro lado da parede.",
      steps: ["Arraste «não passa» entre o símbolo do monstro e o da parede", "Veja o que o monstro faz"],
      praise: "Monstro + não passa + parede: o monstro não pode atravessar paredes.",
    },
    "eyes": {
      title: "Os olhinhos",
      mission: "Veja o que uma regra diz, sem jogar.",
      steps: ["Arraste os olhinhos até o quadradinho, ao lado da estrela"],
      praise: "Os olhinhos mostram o que a regra diz: aqui, a estrela vira um coração.",
    },
    "sun": {
      title: "O sol aparece",
      mission: "Faça o sol aparecer sobre as nuvens.",
      steps: ["Arraste «teletransporta» entre o símbolo do sol e o da nuvem", "Mova a ovelha até o capim"],
      praise: "Quando a ovelha bate no capim, o sol aparece na nuvem. Uma colisão pode fazer coisas aparecerem.",
    },
    "eat-all": {
      title: "Coma muita fruta, e estrelas também",
      mission: "Que o personagem faça sumir todas as maçãs e estrelas.",
      steps: ["Arraste o buraco negro para onde ele deve ir", "Agora passe por cima das maçãs e das estrelas"],
      praise: "Uma regra para cada coisa que se come. Com duas regras, o personagem come duas coisas.",
    },
    "portal": {
      title: "O portal",
      mission: "Teletransporte-se para o outro lado da parede e chegue à estrela.",
      steps: ["Arraste «teletransporta» entre o símbolo do personagem e o da porta", "Entre no portal e alcance a estrela"],
      praise: "Personagem bate no portal → o personagem aparece na porta. É assim que um personagem se teletransporta.",
    },
    "pull": {
      title: "Puxar coisas",
      mission: "Leve a caixa junto com você até a estrela.",
      steps: ["Arraste «puxa» entre o símbolo do personagem e o da caixa", "Leve a caixa até a estrela: a caixa vai atrás de você"],
      praise: "Personagem + puxa + caixa: a caixa vai atrás do personagem.",
    },
    "nobody-passes": {
      title: "Ninguém passa",
      mission: "Deixe o fantasma preso e chegue à estrela.",
      steps: ["Arraste o coringa ao lado de «não passa»", "Leve o personagem até a estrela. O fantasma não consegue alcançá-lo"],
      praise: "O coringa vale para qualquer coisa: nenhum personagem atravessa a parede, nem o fantasma nem você.",
    },
    "food": {
      title: "Uma dieta equilibrada",
      mission: "Que o personagem coma maçãs e peixe.",
      steps: ["Arraste «está dentro de» entre o símbolo do peixe e o de comida", "Agora coma tudo"],
      praise: "A maçã está dentro da ideia de comida, o peixe também: uma só regra permite comer comidas diferentes. Isso é uma categoria.",
    },
    "one-rule": {
      title: "Uma regra para muitos objetos",
      mission: "Coma três coisas diferentes com uma regra só.",
      steps: ["Arraste o símbolo «comida» e complete a regra", "Agora coma tudo"],
      praise: "Três coisas diferentes, uma regra só: a regra fala da categoria abstrata, e não de cada coisa concreta.",
    },
    "day-night": {
      title: "Do dia vem a noite",
      mission: "Transforme o sol em lua.",
      steps: ["Arraste «vira» entre o símbolo do sol e o da lua", "Agora ponha os olhinhos ao lado do símbolo do sol, o de cima"],
      praise: "Sol → lua: o sol vira lua. Essa é uma regra que substitui um símbolo por outro.",
    },
    "chain": {
      title: "Transformação em cadeia",
      mission: "Transforme o sol em estrela, passo a passo.",
      steps: ["Arraste «vira» entre o símbolo da lua e o da estrela", "Agora ponha os olhinhos ao lado do símbolo do sol de cima"],
      praise: "Sol → lua → estrela: as substituições se encadeiam até o fim.",
    },
    "break-rule": {
      title: "Apague a regra jogando",
      mission: "Quebre a sua própria regra para poder atravessar a parede.",
      steps: ["Empurre algum símbolo da regra que impede você de atravessar a parede", "Agora atravesse a parede até a estrela"],
      praise: "O personagem pode mudar regras. O jogo muda as próprias regras enquanto você joga.",
    },
    "rule-by-playing": {
      title: "Crie a regra jogando",
      mission: "Monte a regra empurrando símbolos e leve a caixa até a estrela.",
      steps: ["Empurre «puxa» entre os dois símbolos soltos", "Agora leve a caixa até a estrela: a caixa vai atrás de você"],
      praise: "Você montou uma regra sem pegar peças de baixo: empurrando símbolos pelo tabuleiro.",
    },
    "fire": {
      title: "Na mosca",
      mission: "Acerte uma flecha no fantasma.",
      steps: ["Arraste “corre até” ao quadradinho, entre a flecha e o fantasma", "Toque na barra de espaço"],
      praise: "A barra de espaço faz a flecha aparecer na nave, e a flecha corre até o fantasma. Duas regras, uma flechada.",
    },
    "missile": {
      title: "Faça sumir",
      mission: "Derrube o fantasma com uma flechada.",
      steps: ["Arraste o buraco negro até o quadradinho no fim da regra de cima", "Toque na barra de espaço"],
      praise: "Quando a flecha bate no fantasma, o fantasma cai no buraco negro. Some para sempre.",
    },
    "next": {
      title: "O número seguinte",
      mission: "Relacione os números.",
      steps: ["Ponha os olhinhos ao lado do 2 de cima", "Agora arraste o 3 até o quadradinho: depois do 2 vem o 3"],
      praise: "No Diálogo não há números: você os inventa. “Seguinte de 2 → 3” é uma regra como qualquer outra.",
    },
    "score": {
      title: "Pontos",
      mission: "Faça os pontos subirem quando você toca uma estrela.",
      steps: ["Arraste “aponta para” ao quadradinho no fim da regra", "Ponha os olhinhos ao lado dos pontos", "Bata nas duas estrelas e olhe os pontos"],
      praise: "Bater não coloca um número: troca a regra «pontos → 0» por «pontos → 1», e assim por diante. Soma um cada vez.",
    },
    "add-zero": {
      title: "Zero mais um número",
      mission: "Represente a soma de zero e um número.",
      steps: ["Ponha os olhinhos ao lado do 2 de cima", "Agora arraste a ideia de «número» até o quadradinho do fim"],
      praise: "Zero mais um número é esse número. A soma começa com essa regra: o caso base.",
    },
    "build-chess": {
      title: "Xadrez",
      mission: "Toque no lápis e desenhe uma peça preta",
      steps: ["Toque no lápis e desenhe uma peça preta", "Agora desenhe uma peça branca", "Ponha uma peça preta e uma branca no tabuleiro", "Monte a regra: peça preta · setas", "Monte a regra de comer: preta · bate · branca · vira · branca · teletransporta · buraco negro", "Coma a peça branca"],
      praise: "Você montou um xadrez pequeno: suas peças, suas regras. O de verdade acrescenta categorias: “peça preta” para todas as pretas.",
    },
  },
};
