// 中文教程文本。一句一个动作，用看得见的东西命名。
export const zh = {
  ui: {
    "nav.play": "教程",
    "nav.home": "首页",
    "nav.mine": "我的",
    "nav.badges": "徽章",
    "nav.create": "新建",
    "mine.title": "我的",
    "mine.projects": "个项目",
    "mine.badges": "个徽章",
    "badges.title": "徽章",
    "app.title": "Diálogo 入门",
    "play.title": "Diálogo 入门",
    "play.subtitle": "入门教程：先玩，学会规则，然后下载 Diálogo。",
    "play.goal": "目标",
    "play.previous": "上一关",
    "play.redo": "再玩一次",
    "play.next": "下一个挑战",
    "play.locked": "完成挑战后解锁",
    "play.builds": "做你自己的游戏",
    "play.free": "自由创作",
    "play.startOver": "从头开始",
    "play.startOverConfirm": "从头开始吗？你的挑战和徽章会被清空，项目会保留。",
    "play.freeHint": "做完这些游戏后解锁",
    "language": "语言",
    "sound": "声音",
    "sound.on": "声音：开",
    "sound.off": "声音：关",
    "openFile": "打开 .dialog.ar 文件",
    "more": "更多",
    "open": "打开",
    "copyAndChange": "复制并修改",
    "download": "下载 .dialog.ar",
    "myVersionOf": "我的版本：",
    "mineSuffix": "（我的）",
    "error.open": "打不开这个项目",
    "error.copy": "复制不了这个项目",
    "error.file": "打不开这个文件",
    "error.openNamed": "打不开：",
    "feed.challenge": "挑战",
    "feed.nextChallenge": "你的下一个挑战",
    "feed.play": "玩",
    "feed.live": "运行中",
    "feed.you": "你",
    "feed.empty": "做你的第一个项目",
    "feed.watchOnly": "这个项目只能看，不能控制",
    "category.games": "游戏",
    "category.didactic": "课程",
    "category.mine": "我的",
    "success.title": "你做到了！",
    "success.next": "下一关",
    "success.home": "首页",
    "success.stay": "留下来自己做",
    "success.yours": "现在它是你的了。随便改。你会在“我的”里找到它。",
    "menu.backToStart": "回到开始",
    "menu.forBuilding": "制作工具",
    "menu.setStart": "把这里设为开始",
    "menu.reuse": "使用其他项目的图块",
    "challenge.restart": "重新开始",
    "tray.draw": "画画",
    "tray.drawing": "图画",
    "tray.symbol": "图块",
    "joystick.space": "空格",
    "joystick.enter": "回车",
    "paint.title": "画画",
    "paint.done": "完成",
    "paint.close": "不保存就关闭",
    "paint.brush": "画笔",
    "paint.eraser": "橡皮",
    "paint.bucket": "油漆桶",
    "paint.undo": "撤销",
    "paint.size": "粗细",
    "paint.canvas": "画布",
    "color.black": "黑色",
    "color.orange": "橙色",
    "color.blue": "蓝色",
    "color.brown": "棕色",
    "color.white": "白色",
    "color.red": "红色",
    "color.yellow": "黄色",
    "color.green": "绿色",
    "color.purple": "紫色",
    "color.pink": "粉色",
    "color.cyan": "天蓝色",
    "color.gray": "灰色",
    "badge.first-drop": "第一个图块|在棋盘上放一个图块",
    "badge.rule": "第一条规则|用图块拼出一条规则",
    "badge.first-move": "动起来|第一次让角色移动",
    "badge.artist": "小画家|画一个新图块",
    "badge.detective": "小侦探|用眼睛看看规则在说什么",
    "badge.explorer": "探索者|打开三个项目",
    "badge.remix": "发明家|复制一个项目并修改",
    "badge.saver": "收藏家|保存一个自己的项目",
    "badge.world": "完成一个世界|完成一个世界里的所有挑战",
    "badge.ladder": "冠军|完成所有挑战",
    "end.title": "恭喜你！",
    "end.text": "你已经懂得这门语言的基础了。接着跟着视频教程继续做项目吧：下一步是下载 Diálogo。",
    "end.download": "下载 Diálogo",
    "end.watch": "第 1 课：国际象棋（视频）",
    "end.later": "现在不用",
    "world.primeros": "第一步",
    "world.choques": "碰撞",
    "world.categorias": "类别",
    "world.sustitucion": "替换",
    "world.metaprogramacion": "会变的规则",
    "world.naves": "飞船与时间",
    "world.numeros": "数字",
    "world.puntos": "分数",
    "world.builds": "做你自己的游戏",
  },
  challenges: {
    "reach-star": {
      title: "走到星星",
      mission: "让角色走到星星那里。",
      steps: ["用方向键把角色带到星星那里"],
      praise: "角色就在方向键旁边：所以它会动。",
    },
    "make-rule": {
      title: "拼出规则",
      mission: "让角色动起来，再走到星星那里。",
      steps: ["把方向键拖到小方格里，放在角色旁边", "它动起来了！带它走到星星那里"],
      praise: "角色 + 方向键 = 它会动。这就是一条规则。",
    },
    "eat-star": {
      title: "吃掉星星",
      mission: "让角色把棋盘上所有星星都清掉。",
      steps: ["把黑洞拖到规则末尾的小方格里", "现在去撞这两颗星星"],
      praise: "角色撞到星星时，星星就掉进黑洞：永远消失了。",
    },
    "draw": {
      title: "画一个",
      mission: "画你自己的角色。",
      steps: ["点铅笔。画你自己的角色"],
      praise: "你的画现在是一个角色了。接下来我们让它动起来。",
    },
    "bring-to-life": {
      title: "让它活起来",
      mission: "让你的画活起来，走到星星那里。",
      steps: ["把你的画拖到小方格里，放在方向键旁边", "你的画会动了！带它走到星星那里"],
      praise: "你的画 + 方向键 = 你的画会动。这条规则是你拼的。",
    },
    "run": {
      title: "怪兽会跑",
      mission: "让怪兽自己跑到星星那里。",
      steps: ["把“跑向”拖到小方格里，放在怪兽和星星中间", "看：怪兽自己跑起来了"],
      praise: "怪兽 + 跑向 + 星星：你什么都不用碰，怪兽自己就跑到星星那里。",
    },
    "push": {
      title: "推箱子",
      mission: "把箱子推到星星上。",
      steps: ["把“推”拖到小方格里，放在角色和箱子中间", "现在把箱子推到星星那里"],
      praise: "角色 + 推 + 箱子：角色撞到箱子时，箱子就会动。",
    },
    "walls": {
      title: "那面墙",
      mission: "用墙挡住怪兽，别让它追上你。",
      steps: ["把“过不去”拖到小方格里，放在怪兽和墙中间", "看看怪兽会怎么样"],
      praise: "怪兽 + 过不去 + 墙：怪兽在跑，但墙把它挡住了。",
    },
    "eyes": {
      title: "眼睛",
      mission: "不用玩，也能看出一条规则在说什么。",
      steps: ["把眼睛拖到小方格里，放在星星旁边"],
      praise: "眼睛会显示规则在说什么：这里，星星变成了爱心。",
    },
    "sun": {
      title: "太阳出来了",
      mission: "让太阳从云上出来。",
      steps: ["把“传送”拖到小方格里，放在太阳和云中间", "把小羊带到草那里"],
      praise: "小羊撞到草的时候，太阳就出现在云上。碰撞能让东西出现。",
    },
    "eat-all": {
      title: "全部吃掉",
      mission: "让角色把所有苹果和所有星星都清掉。",
      steps: ["把黑洞拖到小方格里", "现在把苹果和星星都吃掉"],
      praise: "每吃一样东西就要一条规则。有两条规则，角色就能吃两样。",
    },
    "portal": {
      title: "传送门",
      mission: "让角色穿过墙，走到星星那里。",
      steps: ["把“传送”拖到小方格里，放在角色和门中间", "进传送门，然后走到星星那里"],
      praise: "角色撞到传送门 → 角色出现在门那里。墙就是这样穿过去的。",
    },
    "pull": {
      title: "拉箱子",
      mission: "把箱子一起带到星星那里。",
      steps: ["把“拉”拖到小方格里，放在角色和箱子中间", "把角色带到星星那里。箱子会跟着"],
      praise: "角色 + 拉 + 箱子：箱子跟在角色后面走。",
    },
    "nobody-passes": {
      title: "谁都过不去",
      mission: "把幽灵挡在外面，自己走到星星那里。",
      steps: ["把万能牌拖到小方格里，放在“过不去”前面", "把角色带到星星那里。幽灵过不来"],
      praise: "万能牌代表任何东西：谁都过不了这面墙，幽灵不行，你也不行。",
    },
    "food": {
      title: "都是食物",
      mission: "让角色吃苹果也吃鱼：营养均衡。",
      steps: ["把“属于”拖到小方格里，放在鱼和食物中间", "现在把东西都吃掉"],
      praise: "苹果属于食物，鱼也属于食物：一条规则就能把两样都吃掉。这就是一个类别。",
    },
    "one-rule": {
      title: "一条规则管全部",
      mission: "用一条规则吃掉三样不同的东西。",
      steps: ["把“食物”拖到规则的两个小方格里", "现在把东西都吃掉"],
      praise: "三样不同的东西，一条规则：规则说的是类别，不是每一样东西。",
    },
    "day-night": {
      title: "白天和黑夜",
      mission: "把太阳变成月亮。",
      steps: ["把“变成”拖到小方格里，放在太阳和月亮中间", "现在把眼睛放在上面那个太阳旁边"],
      praise: "太阳 → 月亮：太阳变成了月亮。这就是一次替换。",
    },
    "chain": {
      title: "一串替换",
      mission: "一步一步把太阳变成星星。",
      steps: ["把“变成”拖到小方格里，放在月亮和星星中间", "现在把眼睛放在上面那个太阳旁边"],
      praise: "太阳 → 月亮 → 星星：替换会一个接一个，直到最后。",
    },
    "break-rule": {
      title: "打破规则",
      mission: "打破你自己的规则，好穿过这面墙。",
      steps: ["把“过不去”推出规则", "现在穿过墙，走到星星那里"],
      praise: "你推动了自己程序的一块。游戏在你玩的时候改了自己的规则。",
    },
    "rule-by-playing": {
      title: "边玩边拼规则",
      mission: "推动零件拼出一条规则，再走到星星那里。",
      steps: ["把“拉”推进规则的小方格里", "现在把角色带到星星那里。箱子会跟着"],
      praise: "你没有从下面取图块就拼出了一条规则：在棋盘上推动它的零件。",
    },
    "fire": {
      title: "正中目标",
      mission: "用箭射中幽灵。",
      steps: ["把“跑向”拖到小方格里，放在箭和幽灵中间", "按一下空格键"],
      praise: "空格键让箭出现在飞船上，箭就跑向幽灵。两条规则，一发命中。",
    },
    "missile": {
      title: "让它消失",
      mission: "打下幽灵，让它消失。",
      steps: ["把黑洞拖到上面那条规则末尾的小方格里", "按一下空格键"],
      praise: "再加一条规则：箭撞到幽灵时，幽灵掉进黑洞。永远消失了。",
    },
    "next": {
      title: "下一个数",
      mission: "发明数字 3。",
      steps: ["把眼睛放在上面的 2 旁边", "现在把 3 拖到小方格里：2 的下一个是 3"],
      praise: "Diálogo 里没有数字：数字是你发明的。“2 的下一个 → 3”和别的规则一样。",
    },
    "score": {
      title: "分数",
      mission: "吃到星星时让分数往上加。",
      steps: ["把“指向”拖到规则末尾的小方格里", "把眼睛放在分数旁边", "撞这两颗星星，看看分数"],
      praise: "撞击不是直接写上一个数：它把“分数 → 0”换成了“分数 → 下一个”。每次加一。不用变量。",
    },
    "add-zero": {
      title: "加零",
      mission: "教 Diálogo 怎么加零。",
      steps: ["把眼睛放在上面的 2 旁边", "现在把“数字”拖到规则末尾的小方格里"],
      praise: "零加一个数就是那个数。加法就从这条规则开始：这是基础情形。",
    },
    "build-chess": {
      title: "国际象棋",
      mission: "点铅笔，画一个黑棋子",
      steps: ["点铅笔，画一个黑棋子", "现在画一个白棋子", "把一个黑棋子和一个白棋子放到棋盘上", "拼出规则：黑棋子 · 方向键", "拼出吃子规则：黑 · 撞 · 白 · 变成 · 白 · 传送 · 黑洞", "吃掉白棋子"],
      praise: "你做了一盘小小的国际象棋：你的棋子，你的规则。真正的那盘还会加上类别：用“黑棋子”代表所有黑子。",
    },
  },
};
